version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/ruby:2.4-node-browsers
    steps:
      - checkout
      - run:
          name: install asciidoctor
          command: gem install asciidoctor:1.5.8 asciidoctor-diagram:1.5.19 asciidoctor-pdf:1.5.0.rc2 asciidoctor-epub3:1.5.0.alpha.11 epubcheck:3.0.1 coderay
      - run:
          name: mkdir
          command: mkdir ./dist
      - run:
          command: asciidoctor -D dist -o index.html index.ja.adoc
      - run:
          command: asciidoctor-pdf -D dist -o zalando-guidelines-ja.pdf index.ja.adoc
      - run:
          command: asciidoctor-epub3 -D dist -o zalando-guidelines-ja.epub index.ja.adoc
      - run:
          command: cp -r assets ./dist
      - run:
          name: install netlify-cli
          command: npm install netlify-cli
      - run:
          name: deploy to netlify
          command: node_modules/.bin/netlify deploy --auth="$netlify_token" --dir="output" --site="ce58be82-b5e0-4e97-acb5-d3144d410eac"
