[[common-headers]]
= 共通のヘッダ

このセクションでは私たちが毎日使う中で疑問に思ったり、あまり知られてないけれど
特定の状況では役に立ったりするいくつかのヘッダについて記述します。

[#178]
== {MUST} 正しいContentヘッダを使う

Contentやエンティティに関するヘッダには、`Content-`のプレフィクスが付いています。
これらにはメッセージボディの内容に関することが書かれていて、HTTPリクエストとレスポンスの両方で使用されます。
共通的に使われるContentヘッダは次のようなものですが、その限りではありません。

* https://tools.ietf.org/html/rfc6266[`Content-Disposition`] はファイルとして
保存されることを意図したり、そのときのデフォルトのファイル名を与えるのに使う。
* https://tools.ietf.org/html/rfc7231#section-3.1.2.2[`Content-Encoding`]
はContentに適用される圧縮/暗号アルゴリズムを示す。
* https://tools.ietf.org/html/rfc7230#section-3.3.2[`Content-Length`]
はContentの長さをbyte長で示す。
* https://tools.ietf.org/html/rfc7231#section-3.1.3.2[`Content-Language`]
indicates that the body is meant for people literate in some human
language(s).
* https://tools.ietf.org/html/rfc7231#section-3.1.4.2[`Content-Location`]
はボディが別の場所にあることを示す
(<<179>> により詳細があります)。
* https://tools.ietf.org/html/rfc7231#section-3.1.1.5[`Content-Type`]
は、ボディのメディアタイプを示す。

[#133]
== {MAY} 標準のヘッダを使う

http://en.wikipedia.org/wiki/List_of_HTTP_header_fields[このリスト]
を使い、OpenAPI定義にサポートするヘッダを記述します。

[#179]
== {MAY} Content-Location ヘッダを使う

Content-Location ヘッダは _任意_ であり、成功した書き込み操作(PUT, POST, PATCH)や読み込み操作(GET, HEAD)
で使われ、キャッシュ位置を示したり、リソースの実際の場所を受信者に通知したりします。
これによりクライアントはリソースを識別し、このヘッダの付いたレスポンスを受け取ったらローカルコピーを
更新することができるのです。

Content-Locationヘッダは、次のユースケースを実現するのに使われます。

* GETやHEADで、リクエストされたURIとは異なる場所が、
返されるリソースはコンテントネゴシエーションに依存したものであったり、リソース固有の識別子を与えることを
示すのに使われる。
* PUTやPATCHでは、リクエストされたURIと同一の場所を指し、
返却されたリソースが、新しく生成/更新されたリソースの現在の表現であることを明示するのに使われる。
* POSTやDELETEでは、
リクエストされたアクションに対するレスポンスに、ステータスレポートリソースが含まれることを示すのに使われる。

*注意*: Content-Locationヘッダを使用する際には、Content-Typeヘッダも正しく
設定しなければならない。例えば、以下のように。

[source,http]
----
GET /products/123/images HTTP/1.1

HTTP/1.1 200 OK
Content-Type: image/png
Content-Location: /products/123/images?format=raw
----

[#180]
== {SHOULD} Content-Locationの代わりにLocationヘッダを使う

セマンティクスやキャッシュに関して、Content-Locationを正しく使うのは
難しいので、私たちはContent-Location の使用を _推奨していません_ 。
たいていの場合、Content-Location特有の曖昧さや複雑さに悩まされる代わりに、
Locationヘッダを使うことで、クライアントにリソースの場所を直接知らせることで十分です。

RFC 7231により詳細があります。
* https://tools.ietf.org/html/rfc7231#section-7.1.2[7.1.2 Location]
* https://tools.ietf.org/html/rfc7231#section-3.1.4.2[3.1.4.2
Content-Location]

[#181]
== {MAY} 処理するプリファレンスを示すためにPreferヘッダを使う

`Prefer` ヘッダは https://tools.ietf.org/html/rfc7240[RFC7240]
で定義されており、クライアントがサーバの振る舞いをリクエストするのに使われます。
https://tools.ietf.org/html/rfc7240[RFC7240] では多くのプリファレンスが
事前定義されていて拡張も可能です。
Prefer ヘッダのサポートは、任意でありAPI設計の裁量次第ですが、
既存のインターネット標準と同様に、独自の"X-"ヘッダを定義して処理することをおすすめします。

`Prefer` ヘッダはAPI定義に次のように定義します。

[source,yaml]
----
Prefer:
  name: Prefer
  description: |
    The RFC7240 Prefer header indicates that particular server
    behaviors are preferred by the client but are not required
    for successful completion of the request.
    # (indicate the preferences supported by the API)

  in: header
  type: string
  required: false
----

`Prefer` をサポートするAPIは、 これまた
https://tools.ietf.org/html/rfc7240[RFC7240]
で定義された `Preference-Applied` ヘッダを返すかもしれません。
これはプリファレンスが適用されたかどうかを指し示すのに使われます。

[#182]
== {MAY} If-Match/If-None-MatchヘッダともにEtagを使う

リソースが作成、更新されるときは、コンフリクトの発生を検知し、'更新データのロスト'や
'重複して作成される'問題を防ぐ必要があります。
https://tools.ietf.org/html/rfc7232[RFC 7232 "HTTP: Conditional Requests"]
にしたがい、
https://tools.ietf.org/html/rfc7232#section-2.3[`ETag`]
ヘッダを
https://tools.ietf.org/html/rfc7232#section-3.1[`If-Match`]
または
https://tools.ietf.org/html/rfc7232#section-3.2[`If-None-Match`]
の条件ヘッダとともに使うことで、それが出来るようになります。
`ETag: <entity-tag>` ヘッダの内容は、(a) レスポンスボディのハッシュ値か、
(b) エンティティの最終更新日時フィールドのハッシュ値、(c) エンティティのバージョンの
番号または識別子の何れかにします。

PUT, POST, PATCHの同時更新操作でコンフリクトが発生したことを検出するために、
サーバは `If-Match: <entity-tag>` ヘッダがあれば、更新エンティティのバージョンが、
リクエストの `<entity-tag>` と一致しているかをチェックしなければなりません。
もし一致するエンティティがなければ、412 - precondition failed のステータスコードを
返すようにします。

他のユースケース、
リソース生成時にコンフリクトを検出する方法としては、
`If-None-Match:` ヘッダに `*` のパラメータを使います。
もしエンティティにマッチするものがあれば、既に同じリソースが作成されていることを
示すので、412 - precondition failed のステータスコードを返します。

`ETag`, `If-Match`, `If-None-Match` ヘッダは、API定義においては次のように
定義されます。

[source,yaml]
----
Etag:
  name: Etag
  description: |
    The RFC7232 ETag header field in a response provides the current entity-
    tag for the selected resource. An entity-tag is an opaque identifier for
    different versions of a resource over time, regardless whether multiple
    versions are valid at the same time. An entity-tag consists of an opaque
    quoted string, possibly prefixed by a weakness indicator.

  in: header
  type: string
  required: false
  example: W/"xy", "5", "7da7a728-f910-11e6-942a-68f728c1ba70"

IfMatch:
  name: If-Match
  description: |
    The RFC7232 If-Match header field in a request requires the server to
    only operate on the resource that matches at least one of the provided
    entity-tags. This allows clients express a precondition that prevent
    the method from being applied if there have been any changes to the
    resource.

  in: header
  type: string
  required: false
  example:  "5", "7da7a728-f910-11e6-942a-68f728c1ba70"

IfNoneMatch:
  name: If-None-Match
  description: |
    The RFC7232 If-None-Match header field in a request requires the server
    to only operate on the resource if it does not match any of the provided
    entity-tags. If the provided entity-tag is `*`, it is required that the
    resource does not exist at all.

  in: header
  type: string
  required: false
  example: "7da7a728-f910-11e6-942a-68f728c1ba70", *
----

別のアプローチについての議論は、<<optimistic-locking>> セクションも参照ください。
