[[common-data-types]]
= 共通のデータ型

広く利用されるデータオブジェクトの定義です。

[#173]
== {SHOULD} 共通のお金オブジェクトを使う

以下のような共通のお金構造を使いましょう。

[source,yaml]
----
include::../models/money-1.0.0.yaml[]
----

Moneyのグローバルスキーマを参照をincludeするとよい。

[source,yaml]
----
SalesOrder:
  properties:
    grand_total:
      $ref: 'https://opensource.zalando.com/restful-api-guidelines/money-1.0.0.yaml#/Money'
----

APIが閉じたデータ型として、Moneyを取り扱わなくてはならないことに注意しましょう。つまり、インスタンス階層で使わることを意味しません。次のような使い方が許されないことを意味します。

[source,json]
----
{
  "amount": 19.99,
  "currency": "EUR",
  "discounted_amount": 9.99
}
----

=== Cons

* https://en.wikipedia.org/wiki/Liskov_substitution_principle[リスコフの置換原則]に違反している。
* 既存のライブラリのサポート(例えば、https://github.com/zalando/jackson-datatype-money[Jackson Datatype Money])にのらない。
* amountが一緒に組み合わさるので、柔軟性が損なわれる。(例えば、複合的な通貨が表現できない)

より良いアプローチはhttps://en.wikipedia.org/wiki/Composition_over_inheritance[継承よりもコンポジション]を使うことです。

[source,json]
----
{
  "price": {
    "amount": 19.99,
    "currency": "EUR"
  },
  "discounted_price": {
    "amount": 9.99,
    "currency": "EUR"
  }
}
----

=== Pros

* 継承がないので、置換原則にまつわる問題が無い。
* 既存のライブラリでサポートされる。
* 結合がない。つまり複合通貨も表現できる。
* 価格は自己記述的になり、アトミックな値となる。

=== 注意

ビットコインのトランザクションのように、高い精度を要求する業務もあるので、API仕様に明記していない限りは、アプリケーションは制限なしの精度を受け取れるように
準備しておかなければなりません。
ユーロの正しい表記を例示します。

* `42.20` or `42.2` = 42 Euros, 20 Cent
* `0.23` = 23 Cent
* `42.0` or `42` = 42 Euros
* `1024.42` = 1024 Euros, 42 Cent
* `1024.4225` = 1024 Euros, 42.25 Cent

特定の言語でこのインタフェースを実装したり計算したりする際には、
"amount"フィールドを決して`float`や`double`型に変換してはなりません。
そうしないと精度が失われてしまいます。代わりにJavaの
https://docs.oracle.com/javase/8/docs/api/java/math/BigDecimal.html[`BigDecimal`]のような正確なフォーマットを使いましょう。
詳細は http://stackoverflow.com/a/3730040/342852[Stack Overflow]

いくつかのJSONパーサ(例えばNodeJS)は、デフォルトでnumberをfloatに変換してしまいます。
メリデメの議論を経て、私たちは金額のフォーマットに"decimal"を使うことに決めました。
OpenAPIフォーマットの標準ではないけれど、パーサがnumberをfloatやdoubleに変換してしまうことを避けることができるからです。

[#174]
== {MUST} 共通のフィールド名やセマンティクスを使う

複数の場所で使われるフィールドの型があります。すべてのAPI実装にわたって一貫性を保つために、
どんなときでも適用可能な共通のフィールド名とセマンティクスを使わなければなりません。

[[generic-fields]]
=== 一般的なフィールド

APIに繰り返し出てくるフィールドは以下のようなものです。

* [[id]]{id}: オブジェクトのID。 IDは数値でなく文字列でなくてはなりません。IDは文書化されているコンテキストの範囲でユニークかつ不変です。一度オブジェクトに付与されたら変更されてはならないし、再利用してもいけません。
* [[xyz_id]]{xyz_id}: オブジェクトが別のオブジェクトのIDを持つ場合、相手オブジェクト名に`\_id` を付与した名前を使いましょう。 (e.g. `customer_number` ではなく`customer_id`; 子ノードから親ノードを参照する場合は、たとえ両方が`Node`型であっても、`parent_node_id` とします)
* [[created_at]]{created_at} オブジェクトが作られた日時。`date-time` 型でなくてはなりません。
* [[modified_at]]{modified_at}: オブジェクトが更新された日時。`date-time` 型でなくてはなりません。
* [[type]]{type}: オブジェクトの種類。このフィールドの型はstringとするべきです。typeはエンティティについてのランタイム情報を与えます。
* [[etag]]{etag}: <<158, 埋め込みサブリソース>>の<<182, ETag>>。続く{PUT}/{PATCH}の呼び出しで{ETag}を渡すのに使われる。(<<etag-in-result-entities>>参照)

JSONスキーマの例:

[source,yaml]
----
tree_node:
  type: object
  properties:
    id:
      description: このノードの識別子
      type: string
    created_at:
      description: このノードがいつ作られたか
      type: string
      format: 'date-time'
    modified_at:
      description: このノードが最後に更新されたのはいつか
      type: string
      format: 'date-time'
    type:
      type: string
      enum: [ 'LEAF', 'NODE' ]
    parent_node_id:
      description: このノードの親ノードの識別子
      type: string
  example:
    id: '123435'
    created: '2017-04-12T23:20:50.52Z'
    modified: '2017-04-12T23:20:50.52Z'
    type: 'LEAF'
    parent_node_id: '534321'
----

これらのプロパティはいつも必要というわけではありませんが、これを慣例にしておくことで、
APIクライアント開発者にとってZalandoリソースの共通理解が容易になるわけです。
異なる名前が使われたり、APIごとにこれらの型が違ったりすると、API利用者にとっては不便なものになってしまいますからね。

[[link-relation-fields]]
=== リンク関連フィールド

ページネーションとコレクション上での繰り返しをするために、シンプルなハイパーテキスト制御を使って一貫したルックアンドフィールを提供するには、レスポンスオブジェクトは、以下の共通パターンにしたがうべきです。

* [[self]]{self}: 同一のコレクションオブジェクトまたはページを指し示す、ページネーションレスポンスまたはオブジェクトへのリンクおよびカーソル
* [[first]]{first}: 最初のコレクションオブジェクトまたはページを指し示す、ページネーションレスポンスまたはオブジェクトへのリンクおよびカーソル
* [[prev]]{prev}: 前のコレクションオブジェクトまたはページを指し示す、ページネーションレスポンスまたはオブジェクトへのリンクおよびカーソル
* [[next]]{next}: 次のコレクションオブジェクトまたはページを指し示す、ページネーションレスポンスまたはオブジェクトへのリンクおよびカーソル
* [[last]]{last}: 最後のコレクションオブジェクトまたはページを指し示す、ページネーションレスポンスまたはオブジェクトへのリンクおよびカーソル

ページネーションのレスポンスは、ページ内容を送るためのArrayフィールドを追加で持ちます。

* [[items]]{items}: 現在のページのすべてのアイテムをもつリソースの配列 ({items} はリソースの名前でもよい).

ユーザ体験を単純化するため、適用されたクエリフィルタを使います。({GET-with-body}も参照)

* [[query]]{query}: コレクションリソースをフィルタする検索リクエストでの適用されたクエリフィルタを含むオブジェクト。

結果として、<<161, ページネーションリンク>>を使った標準のレスポンスページは、以下のようになります。

[source,yaml]
----
ResponsePage:
  type: object
  properties: 
    self:
      description: 現在のページを指すページネーションリンク。
      type: string
      format: uri
    first:
      description: 最初のページを指すページネーションリンク。
      type: string
      format: uri
    prev:
      description: 前のページを指すページネーションリンク。
      type: string
      format: uri
    next:
      description: 次ページを指すページネーションリンク。
      type: string
      format: uri
    last:
      description: 最後のページを指すページネーションリンク。
      type: string
      format: uri

     query:
       description: >
        コレクションリソースに適用されたクエリフィルタを含むオブジェクト。
       type: object
       properties: ...

     items:
       description: コレクションアイテムのArray。
       type: array
       required: false
       items:
         type: ...
----

レスポンスページは、コレクションや現在のページに関する追加のメタデータを含むかもしれません。

[[address-fields]]
=== 住所フィールド

住所の構造は国の違いを含む様々な機能、ユースケースに影響します。
住所に関するすべての属性は、以下で定義された名前とセマンティクスにしたがいます。

[source,yaml]
----
addressee:
  description: a (natural or legal) person that gets addressed
  type: object
  properties:
    salutation:
      description: |
        a salutation and/or title used for personal contacts to some
        addressee; not to be confused with the gender information!
      type: string
      example: Mr
    first_name:
      description: |
        given name(s) or first name(s) of a person; may also include the
        middle names.
      type: string
      example: Hans Dieter
    last_name:
      description: |
        family name(s) or surname(s) of a person
      type: string
      example: Mustermann
    business_name:
      description: |
        company name of the business organization. Used when a business is
        the actual addressee; for personal shipments to office addresses, use
        `care_of` instead.
      type: string
      example: Consulting Services GmbH
  required:
    - first_name
    - last_name

address:
  description:
    an address of a location/destination
  type: object
  properties:
    care_of:
      description: |
        (aka c/o) the person that resides at the address, if different from
        addressee. E.g. used when sending a personal parcel to the
        office /someone else's home where the addressee resides temporarily
      type: string
      example: Consulting Services GmbH
    street:
      description: |
        the full street address including house number and street name
      type: string
      example: Schönhauser Allee 103
    additional:
      description: |
        further details like building name, suite, apartment number, etc.
      type: string
      example: 2. Hinterhof rechts
    city:
      description: |
        name of the city / locality
      type: string
      example: Berlin
    zip:
      description: |
        zip code or postal code
      type: string
      example: 14265
    country_code:
      description: |
        the country code according to
        [iso-3166-1-alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2)
      type: string
      example: DE
  required:
    - street
    - city
    - zip
    - country_code
----

特定データ型におけるフィールドのグルーピングやカーディナリティは、特定のユースケースに基づいています。
(例えば、宛先をモデル化するときは受取人と住所のフィールドの組み合わせをるけれども、ユーザと住所をモデル化するときは、受取人と住所は別にする、ということです)
