[[deprecation]]
= 廃止予定

APIエンドポイント(または、そのバージョン)を、廃止する必要が出てくることがあります。例えば、もはやサポートされていないフィールドや、業務機能ごと停止したいエンドポイントなど、様々な理由があることでしょう。これらのエンドポイントは、利用者に使われている限りは、破壊的変更は許されません。利用者にとって必要な変更を整理し、廃止予定のエンドポイントがAPIの変更がデプロイされる前に使われないようにするため、「廃止予定ルール」を適用します。

[#185]
== {MUST} クライアントの承認を得る

API(またはAPIのバージョン)を停止する前に、すべてのクライアントに、そのエンドポイントを停止してもよいという同意をとらなければなりません。(移行マニュアルを提供するなどして) 新しいエンドポイントへ移行の手助けをしてください。
すべてのクライアントが移行が完了したら、廃止予定のAPIを停止できます。

[#186]
== {MUST} 外部パートナーは廃止までの猶予期間に同意をしなければならない

もし外部パートナーによってAPIが使われていたら、廃止予定をアナウンスしたあとAPIの現実的な移行猶予期間を定義しなければなりません。外部パートナーはAPIを使い始める前に、この最小の移行猶予期間に同意しなければなりません。

[#187]
== {MUST} API定義に廃止予定を反映する

APIの廃止予定は、OpenAPI定義に含まれなくてはなりません。とあるメソッド、パス全体、(複数のパス含む)APIエンドポイントまるごと、いずれにしてもそれらを廃止予定とするならば、メソッド/パスエレメントそれぞれに `deprecated: true` を設定しなければなりません。
もし廃止予定がより詳細なレベルで必要であれば、影響する要素に `deprecated=true` を設定したうえで、`description` に説明書きを加えます。

`deprecated` に `true` が設定されたら、クライアントが代わりに使うべきものやAPIがいつ廃止されるのかを、API定義の `description` に記述しなければなりません。

[#188]
== {MUST} 廃止予定APIとAPIエンドポイントの利用状況をモニタリングする

本番環境で使われるAPIのオーナーは、APIが廃止予定を調整し、コントロールできない
破壊的影響を避けるため、APIが廃止されるまで、廃止予定APIの利用状況をモニタリングしなくてはなりません。
<<193>>も参照ください。

[#189]
== {SHOULD} レスポンスにDeprecationヘッダを付ける

廃止予定フェーズの間、 `Deprecation`  ヘッダを付けましょう。
(https://tools.ietf.org/html/draft-dalal-deprecation-header[draft: RFC Deprecation HTTP Header]をみてください)。
廃止予定日({RFC-7231}#section-7.1.1.1[HTTP Date/Time]形式)を値として付けます。

[source,txt]
-----
Deprecation: Sun, 11 Nov 2018 23:59:59 GMT
-----

`Deprecation`  ヘッダを付けても、APIを廃止することをクライアントの合意を取り付けたことにはならないことに注意しましょう。

*ヒント:* ガイドラインの初期バージョンでは、`Warning` ヘッダを使うようにしていました。しかし、`Warning` ヘッダはあまりその意味がハッキリしないので https://tools.ietf.org/html/draft-ietf-httpbis-cache-06[draft: RFC HTTP Caching] では廃止になるようです。私たちの構文も、 {RFC-7234}#page-29[RFC 7234 -- Warning header] に合っていませんでした。

[#190]
== {SHOULD} Deprecationヘッダのモニタリングを追加する

クライアントはHTTPレスポンスの `Deprecation` ヘッダをモニタリングし、APIが将来廃止されることがあるかどうかを注視してください。

*ヒント:* ガイドラインの初期バージョンでは、`Warning` ヘッダを使っていました。<<189>>を参照してください。

[#191]
== {MUST} 廃止予定APIは新規に利用し始めてはならない。

クライアントは、廃止予定のものを利用し始めてはなりません。
