[[deprecation]]
= 廃止予定

APIエンドポイント(または、そのバージョン)を、廃止する必要が出てくることもあるでしょう。
例えば、もはやサポートされていないフィールドや、業務機能ごと停止したいエンドポイントなど、様々な理由が
あることでしょう。
これらのエンドポイントは、利用者に使われている限りは、破壊的変更は許されません。
利用者にとって必要な変更を整理し、廃止予定のエンドポイントが、
APIの変更がデプロイされる前に使われないようにするため、「廃止予定ルール」を適用します。

[#185]
== {MUST} クライアントの承認を得る

API(またはAPIのバージョン)を停止する前に、すべてのクライアントに、
そのエンドポイントを停止してもよいという同意をとらなければなりません。
(移行マニュアルを提供するなどして) 新しいエンドポイントへ移行の手助けをしてください。
すべてのクライアントが移行が完了したら、廃止予定のAPIを停止できます。

[#186]
== {MUST} 外部パートナーは廃止までの猶予期間に同意をしなければならない

もし外部パートナーによってAPIが使われていたら、廃止予定をアナウンスしたあとAPIの
現実的な移行猶予期間を定義しなければなりません。
外部パートナーはAPIを使い始める前に、この最小の移行猶予期間に同意しなければなりません。

[#187]
== {MUST} API定義に廃止予定を反映する

APIの廃止予定は、OpenAPI定義に含まれなくてはなりません。
とあるメソッド、パス全体、(複数のパス含む)APIエンドポイントまるごと、いずれにしても
それらを廃止予定とするならば、メソッド/パスエレメントそれぞれに `deprecated=true` を
設定しなければなりません。
(OpenAPI 2.0ではこのレベルでしか廃止予定は定義できません)
もし廃止予定が(クエリパラメータ、ペイロードなど)より詳細なレベルで必要であれば、
影響するメソッド/パスエレメントに `deprecated=true` を設定したうえで、
`description` に説明書きを加えます。

`deprecated` に `true` が設定されたら、クライアントが代わりに使うべきものや
APIがいつ廃止されるのかを、API定義の `description` に記述しなければなりません。

[#188]
== {MUST} 廃止予定APIの利用状況をモニタリングする

本番環境で使われるAPIのオーナーは、APIが廃止予定を調整し、コントロールできない
破壊的影響を避けるため、APIが廃止されるまで、廃止予定APIの利用状況をモニタリングしなくてはなりません。
<<193>>も参照ください。

[#189]
== {SHOULD} レスポンスに警告ヘッダを付ける

廃止予定フェーズの間、 `Warning` ヘッダを付けましょう。
(https://tools.ietf.org/html/rfc7234#section-5.5[RFC 7234 - Warning
header] をみてください)。
`Warning` が付いていたら、 `warn-code` は `299` を指定し、 `warn-text` は
_"The path/operation/parameter/... \{name} is deprecated and will be removed
by \{date}. Please see \{link} for details."_ の形式にしましょう。
link先は、なぜAPIがもはやサポートされないかと、クライアントがすべきことを記述した
ドキュメントにします。
`Warning`ヘッダを付加しても、クライアントに対しAPI停止の同意を得たとはいえません。

[#190]
== {SHOULD} 警告ヘッダのモニタリングを追加する

クライアントはHTTPレスポンスの `Warning` ヘッダをモニタリングし、
APIが将来廃止されることがあるかどうかを注視してください。

[#191]
== {MUST} 廃止予定APIは新規に利用し始めてはならない。

クライアントは、廃止予定のものを利用し始めてはなりません。
