[[principles]]
= 原則

[[api-design-principles]]
== API設計の原則

SOAPインタフェースをもつSOA WebサービスとRESTを比較すると、前者はユースケースに特化した
操作を中心に据える傾向があります。一方RESTはビジネス(データ)のエンティティを、URIで識別されるリソースとして
どう見せるか、標準化されたCRUDのようなメソッドで、異なる表現やハイパーメディアを使ってどう操作されうるかを中心に据えます。
RESTful APIは、固有のユースケースからは切り離され、クライアント/サーバの結合を疎にする傾向にあります。
さまざまな新しい業務サービスを構築するために、APIのプラットフォームを提供している(コア)サービスのエコシステムに、
より適したものとなっていきます。
私たちは、その機能がインターネットで提供されるのか、イントラネットで提供されるのかに
かかわらず、すべての種類のアプリケーション、(マイクロ)サービスコンポーネントに、RESTfulウェブサービスの原則を適用します。

* 私たちはJSONペイロードをもったRESTベースのAPIを好む
* 私たちはシステムが、真にRESTfulになることを好む
footnote:fielding-restful[R.Fieldingの定義だと、REST APIはHATEOAS(レベル3)をサポート
しなくてはなりません。
私たちのガイドラインは、完全なREST準拠はさほど推奨していません。
(<<hypermedia>>)で示すような限定的なハイパーメディアの使い方をしています。
それでもなお"RESTful API"という言葉を私たちは使います。
他に確立された用語はないし、Webサービス業界ではRESTっぽいものをそう呼んでいるからです。
事実、HATEOASへの完全準拠したAPIは非常に数少ないのが現状です。]

API設計と利用の重要な原則がポステルの原則です。
http://en.wikipedia.org/wiki/Robustness_principle[ロバストネスの原則]
としても知られています。(https://tools.ietf.org/html/rfc1122[RFC 1122] も参照ください)

* 送信するものに関しては厳密に、受信するものに関しては寛容に

_読みましょう:_ RESTful APIの設計スタイルとサービスアーキテクチャについての読み物がいくつかあります。

* Book:
https://www.amazon.de/Irresistible-APIs-Designing-that-developers/dp/1617292559[Irresistable
APIs: Designing web APIs that developers will love]
* Book:
http://www.amazon.de/REST-Practice-Hypermedia-Systems-Architecture/dp/0596805829[REST
in Practice: Hypermedia and Systems Architecture]
* Book: https://leanpub.com/build-apis-you-wont-hate[Build APIs You
Won't Hate]
* InfoQ eBook: http://www.infoq.com/minibooks/emag-web-api[Web APIs:
From Start to Finish]
* Lessons-learned blog:
http://restful-api-design.readthedocs.org/en/latest/[Thoughts on RESTful
API Design]
* Fielding Dissertation:
http://www.ics.uci.edu/\~fielding/pubs/dissertation/top.htm[Architectural
Styles and the Design of Network-Based Software Architectures]

[[api-as-a-product]]
== 製品としてのAPI

前述のとおり、Zalandoは単なるオンラインショップから、価値あるファッションプラットフォームへと
転換しており、ビジネスパートナーのためにSaaP(プラットフォームとしてのソフトウェア)モデル
に続く、製品の豊富な集合を提供しています。
企業として私たちは、これらの製品を(内外問わず)顧客に届けたいのです。

プラットフォームとしての製品とは、(公開)APIで提供される機能群です。
したがってAPIの設計は、製品としての原則に基づくべきなのです。

* APIを製品として扱い、製品のオーナーのように振る舞う
* 顧客の立場に身を置き、彼らのニーズの支持者となる
* 顧客エンジニアにとってAPIがとても魅力的なものになるために、APIのシンプルさ、理解しやすさ、使いやすさを際立たせる
* 長期にわたって、APIをアクティブに改善し、一貫性を維持していく
* 顧客のフィードバックを受け付け、サービスと同レベルのサポートを提供する。

「製品としてのAPI」を掲げることで、サービスのエコシステムはより進化がしやすくなり、
コア機能を組み合わせることによって、新しいビジネスアイデアを早く試すことができるようになります。

APIプラットフォーム上に構築されたイノベーティブな製品サービスと、
オマケとしてAPIが提供されている通常の企業情報システムとでは、
システム統合をサポートしたり、ローカルに最適化されたサーバサイドを実現するところで違いが出てきます。

顧客の具体的なユースケースを理解し、製品として考えAPIの設計のズレとのトレードオフをチェックしましょう。
クライアント側に不要な負担を強いるような、実装の早すぎる最適化を避け、APIの品質とクライアント開発者の使い勝手に最大限の関心をもちましょう。

製品としてのAPIは、(次章で示す)<<100, APIファーストの原則>>と非常に近い関係にあります。
APIファーストは高品質なAPIを、どうエンジニアリングしていくかによりフォーカスしたものです。

[[api-first]]
== APIファースト

APIファーストは、私たちの
https://github.com/zalando/engineering-principles[エンジニアリングとアーキテクチャ原則]
の1つです。

手短にいうと、APIファーストは2つの観点を要求します。

* 実装する前に標準仕様言語を使って、まずAPIを定義する
* 同僚やクライアント開発者から、いち早くレビューのフィードバックを得る

コードの外にAPIを定義することで、私たちは早いレビューフィードバックを促し、
サービスインタフェースの設計が、以下に焦点を当てれるような開発の規律にしたいのです。

* ドメインと要求機能の深い理解
* 一般化された業務エンティティ / リソース (つまり、あるユースケース固有のAPIを避ける)
* WHATとHOWの関心の分離。すなわち、実装の観点から「抽象」をを切り離す。APIはたとえ技術スタックが完全に置き換わったとしても、安定しているべきである。

さらには、標準化された仕様のフォーマットによるAPI定義は、また、

* API仕様の拠り所。それはサービスプロバイダとクライアントのユーザの間の重要な契約の1つとなります。
* APIディスカバリ、API GUI、APIドキュメント、API品質の自動チェックなどのAPI基盤ツール。

APIファーストの要素はまた、このAPIガイドラインと同僚やクライアント開発者から、
早期にレビューフィードバックを得るための、APIガイドラインと標準化されたAPIレビュープロセスです。
APIの品質を高め、アーキテクチャと設計の調整を可能にし、サービスプロバイダの開発サイクルに
クライアントアプリケーションの開発が引きずられないようにするために、私たちにとってピアレビューは重要です。

APIファーストが、私たちの愛する *アジャイル開発の原則と反するものではない* ことは重要なことです。
サービスアプリケーションは徐々に進化していくように、APIもまた進化していきます。
もちろんAPI仕様は異なるサイクルで、繰り返し進化を遂げていくでしょうし、そうあるべきですが、
それらはみな、ドラフトの状態と、 _早期の_ チームレビューおよびピアレビューフィードバックから始まるのです。
APIが変更されると、実装上の懸念と自動化テストのフィードバックからメリットを得ることもあります。
開発のライフサイクルにおいて、生産的な機能がまだない間も、クライアントと変更の調整を続ける限り
破壊的変更を伴いながらAPIを進化させていくことができます。

したがってAPIファーストは、要求とドメインについて100パーセント理解し、完全なAPIを
定義し、ピアレビューでその確信が得られるまで、コードを書いてはいけない、ということを
意味するもの _ではありません_ 。
一方、APIファーストがサービス統合または本番運用開始の後に、API定義の公開したりピアレビューしたりする
バッドプラクティスと衝突があることも明らかです。

早く、できるだけ早くフィートバックを得ることは重要ですが、その前にAPI変更が次の進化のステップへ
の足がかりであることを認識し、既にチーム内レビューで確立された(APIガイドライン遵守を含む)一定水準の品質を、
保つこともまた重要です。
