[[events]]
= イベント

Zalandoのアーキテクチャは疎結合なマイクロサービス中心で作られているので、
私たちは非同期なイベント駆動のアプローチを好みます。
このセクションのガイドラインは、イベントの設計と送信の仕方にフォーカスしたものになります。

*イベント、イベントの型および分類*

イベントは _イベント型_ と呼ぶ項目を使って定義します。
イベント型は送信者によってスキーマを使って宣言され、受信者によって解釈されるイベント構造をもちます。
イベント型は、名前、オーナーアプリケーション(暗黙的にオーナーのチーム)、イベントのカスタムデータ
を定義したスキーマ、スキーマがどう進化していくかを宣言している互換モードなどを、
標準情報として宣言します。
イベント型では、またイベントのバリデーションや強化戦略、イベントストリームの中で、
イベントがどうパーティショニングされうるか、のような補足情報を宣言してもかまいません。

イベント型は、(データ変更カテゴリのように) _イベントカテゴリ_ に属します。
イベントカテゴリはイベントの種類に共通な追加情報を提供します。

イベント型は チームがみな使えるようAPIリソースとして、典型的には _イベント型レジストリ_
に登録して公開します。送受信されるイベントは、そのイベント型の全体の構造と
カスタムデータのためのスキーマに対して、検証済みのものでなくてはなりません。

上述の基本モデルは、 https://github.com/zalando/nakadi[Nakadi プロジェクト]
として元々開発されたものです。
Nakadiはイベント型のレジストリの参照実装であり、
イベントの送受信者のために、pub-subの検証ブローカとして動作します。

[#194]
== {MUST} サービスインタフェースの一部としてイベントを取り扱う

イベントはサービスのREST APIへ同じ立場であり、外界に対してのサービスインタフェースの
一部です。データを送出するサービスは、APIと同じように、イベントを設計における最重要関心事として
扱わなければなりません。
<<はじめに>>で示した「APIファースト」の原則が、イベントに対しても当てはまります。

[#195]
== {MUST} レビューできるようにEventのスキーマを作る

イベントを送出するサービスは、他で使えるようにイベントのスキーマを作らなければなりません。
それだけでなく、レビューのためにもイベントの型定義も作りましょう。

[#196]
== {MUST} イベントスキーマはOpen APIスキーマオブジェクトに準拠する

API仕様にイベントスキーマ仕様も揃えるために、私たちはイベントスキーマの定義にも
Open API仕様を使ってスキーマオブジェクトを定義します。
これは他のAPIで使われているリソースに関するデータ変更を表すイベントにとって、特に便利なものです。

https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#schemaObject[Open
API スキーマオブジェクト] は http://json-schema.org/[JSON Schema Draft 4] の **拡張可能なサブセット** です。
便宜上、私たちは以下にその重要な差異を示します。
詳細は
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#schemaObject[Open
API スキーマオブジェクト仕様] を参照ください。

Open APIスキーマオブジェクトは、いくつかのJSONスキーマキーワードが削除されているので、
イベントスキーマでもこれらは使わないようにしてください。

* `additionalItems`
* `contains`
* `patternProperties`
* `dependencies`
* `propertyNames`
* `const`
* `not`
* `oneOf`

一方でスキーマオブジェクトは、JSONスキーマキーワードを再定義しているものもあります。

* `additionalProperties`: 互換性保証を謳うイベント型には、このフィールドを使うことに関しては制約を設けておたほうがよいでしょう。詳細は<<210>>のガイドラインをみてください。

最後に、スキーマオブジェクトは、JSONスキーマのいくつかのキーワードを _拡張しています_ 。

* `readOnly`: イベントが論理的にイミュータブルであることを意味します。
`readOnly`は冗長とみなされるかもしれませんが無害です。
* `discriminator`: `oneOf` の代替としてポリモーフィズムをサポートするため。
* `^x-`: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#vendorExtensions[ベンダ拡張] の形式でパターン化されたオブジェクトがイベント型スキーマでも使えます。
しかし、汎用目的のバリデータはバリデーションを実行しませんし、無視されるべき処理にフォールバックします。
将来のガイドラインのバージョンでは、イベントのベンダ拡張について、もっとしっかり定義するかもしれません。

[#197]
== {MUST} イベントはイベント型として登録されていることを保証する

Zalandoのアーキテクチャにおいて、イベントは _イベント型_ と呼ばれる
構造を使って登録されます。イベント型では、次のような標準の情報を宣言します。

* イベントカテゴリ。「汎用」や「データ更新」のように、よく知られたものです。
* イベント型の名前
* <<219, イベントの対象オーディエンス>> の定義
* 所有アプリケーション
* イベントのペイロードを定義するスキーマ
* 型の互換モード

イベント型はイベント情報を見つけるのを簡単にし、それが良く構造化されていて、
一貫性があって検証可能であることを保証するものになります。

イベント型のオーナーは、互換モードの選択に気をつけなければなりません。
モードはスキーマの進化の方法を示します。
イベント送信者が既存のイベント受信者に不用意に破壊的変更を与えずに、スキーマを
修正するのにどれだけな柔軟性があるかは、モードの範囲の設計に依存します。

* `none`: たとえ既存のイベント送信者・受信者を破壊しようと、どんなスキーマの修正も受け入れられる。
イベントを検証する際は、スキーマで宣言されていない未定義のプロパティも受け入れなければ
ならない。
* `forward`: スキーマ `S1` は、以前登録されたスキーマ `S0` が `S1` で定義されたイベントを
読むことができる、すなわちイベント受信者は、 <<api-design-principles>> ガイドラインの
ロバストネスの原則にしたがう限り、以前のバージョンを使っている最新のスキーマバージョンで
タグ付けされたイベントも読むことができます。
* `compatible`: これは変更が完全な互換性をもつことを意味します。
最初のスキーマバージョンから、送出されたすべてのイベントが
最新のスキーマでも有効なものであるとき、新しいスキーマ `S1` は、
完全互換です。
compatibleモードでは、既存のスキーマへは新しい任意のプロパティと定義の追加のみ許され、
他の変更は禁止されます。

互換性モードはセマンティックバージョニング (MAJOR.MINOR.PATCH) にしたがう
`version`フィールドに影響します。

* 互換モード `compatible` では、イベント型はPATCHまたはMINORバージョンのみ
変更でき、破壊的変更であるMAJORバージョンアップは許されまない。
* 互換モード `forward` では、イベント型はPATCHまたはMINORバージョンのみ
変更でき、破壊的変更であるMAJORバージョンアップは許されない。
* 互換モード `none` では、イベント型はPATCH、MINOR、MAJORすべてのレベルの
変更ができる。

次の例でこの関係性を説明します。

* イベント型の `title` または `description` を変更することは、PATCHレベルとみなす
* イベント型に任意のフィールドを追加することは、MINORレベルの変更とみなす
* 名前の変更やフィールドの削除、必須フィールドの新規追加など、他のすべての変更はMAJORレベルとみなす。

イベント型の主要な構造は、Open APIオブジェクトとして、以下のように定義されます。

[source,yaml]
----
EventType:
  description: |
    イベント型はスキーマと実行時のプロパティを定義します。必須のフィールドはイベント型の
    作成者が最低限セットすることが期待されているものです。
  required:
    - name
    - category
    - owning_application
    - schema
  properties:
    name:
      description: |
        このEventTypeの名前です。 注意: 全体での一意性と可読性を保つため、
        `<functional-name>.<event-name>` の形式で命名するようにしてください。
      type: string
      pattern: '[a-z][a-z0-9-]*\.[a-z][a-z0-9-]*'
      example: |
        transactions.order.order-cancelled,
        customer.personal-data.email-changed
    audience:
      type: string
      x-extensible-enum:
        - component-internal
        - business-unit-internal
        - company-internal
        - external-partner
        - external-public
      description: |
        イベント型の対象オーディエンス。ルール #219 でのREST APIのオーディエンス定義に相当するものです。
    owning_application:
      description: |
        この `EventType` を所有するアプリケーションの名前です。
        (基盤アプリケーションやサービスレジストリで使われます)
      type: string
      example: price-service
    category:
      description: このEventTypeのカテゴリです。
      type: string
      x-extensible-enum:
        - data
        - general
    compatibility_mode:
      description: |
        このスキーマを発展させていくための互換性モードです。
      type: string
      x-extensible-enum:
        - compatible
        - forward
        - none
      default: forward
    schema:
      description: このEventTypeの最新のペイロードのスキーマです。
      type: object
      properties:
        version:
          description: セマンティックバージョニングに基づくバージョン番号です ("1.2.1"のようなもの)。
          type: string
          default: '1.0.0'
        created_at:
          description: スキーマの作成日時
          type: string
          readOnly: true
          format: date-time
          example: '1996-12-19T16:39:57-08:00'
        type:
          description: |
             スキーマ定義のスキーマ言語です。現在はjson_schema (JSON Schema v04) のみ
             が定義できます。がこれは将来的には他のものも指定可能になるでしょう。
          type: string
          x-extensible-enum:
            - json_schema
        schema:
          description: |
              フィールド型に定義された文法で表現した文字列としてのスキーマ
          type: string
      required:
        - type
        - schema
    created_at:
      description: イベント型が新規作成された日時
      type: string
      pattern: date-time
    updated_at:
      description: イベント型の最終更新日時
      type: string
      pattern: date-time
----

イベント型をサポートしているレジストリのようなAPIは、サポートされたカテゴリやスキーマ形式の
集合を含んだモデルを拡張しているかもしれません。
例えばNakadi APIのイベントカテゴリレジストリは、イベントのバリデーションの宣言や
強化戦略、ストリームの中でどうパーティショニングされるかのような補足情報が
記述できるようになっています。

[#198]
== {MUST} イベントが周知のイベントカテゴリに準拠することを保証する

_イベントカテゴリ_ はイベント型の一般的な分類です。
ガイドラインは2つのカテゴリを定義します。

* 汎用イベント: 汎用目的のカテゴリ
* データ更新イベント: データ統合に基づくレプリケーションに使用されるデータの変更について記述するカテゴリ

カテゴリは将来的に成長していくことが予想されます。

カテゴリとは、イベント送信者が準拠しなくてはならないイベントの種類(データ更新イベントなど)
に関しての標準を、事前に定義した構造で記述したものです。

*汎用イベントカテゴリ*

_汎用イベントカテゴリ_ は、Open API スキーマオブジェクトの定義として、
以下のような構造で表せます。

[source,yaml]
----
GeneralEvent:
  description: |
    汎用目的のイベントの種類です。このイベントに基づくイベントの種類は、
    ドキュメントのトップレベルとして、カスタムスキーマペイロードを定義します。
    ペイロードには、"metadata" フィールドが必要です。
    したがって、このイベント型に基づくイベントのインスタンスは、EventMetadataの定義と、
    カスタムスキーマ定義の両方に準拠することになります。
    以前はこのカテゴリは、業務カテゴリと呼ばれていました。
  required:
    - metadata
  properties:
    metadata:
        $ref: '#/definitions/EventMetadata'
----

汎用イベントカテゴリに属するイベント型は、ドキュメントのトップレベルに
標準情報のための予約されている <<event-metadata,metadata>> フィールドを使って、
カスタムスキーマのペイロードを定義します。
(<<event-metadata,metadata>> の内容は、このセクションのずっと下の方に記述してあります)

注意:

* 以前のガイドラインでは、汎用イベントは _業務イベント_ と呼んでいた。
カテゴリの構造が、他の種類のイベントでも使われるようになったので、
チームの使い方を反映して名前を変更した。
* 汎用イベントは元の業務プロセスを駆動するイベントを定義する目的でも、今でも有用だし、そういう使い方にはおすすめする。
* Nakadiのブローカーは、汎用カテゴリを業務カテゴリとして参照し、イベント型は「business」というキーワードで登録される。それ以外のJSONの構造は同じである。

カテゴリの使い方に関するガイドは <<201>> により詳細があります。

*データ更新イベントカテゴリ*

_データ更新イベントカテゴリ_ は、Open API スキーマオブジェクトの定義として、
以下のような構造で表せます。

[source,yaml]
----
DataChangeEvent:
  description: |
    エンティティの変更の表現です。必須フィールドは、送信者によって送られることが
    期待され、そうでないフィールドはpub/subブローカのような仲介者によって、
    付加される可能性があります。 イベント型に基づくイベントのインスタンスは、
    DataChangeEventの定義とカスタムスキーマ定義の両方に準拠します。
  required:
    - metadata
    - data_op
    - data_type
    - data
  properties:
    metadata:
      description: このイベントのメタデータです。
      $ref: '#/definitions/EventMetadata'
    data:
      description: |
        イベント型のカスタムペイロードを含みます。ペイロードは、メタデータオブジェクトの
        `event_type` フィールドに宣言されたイベント型と関連したスキーマに準拠しなければ
        なりません。
      type: object
    data_type:
      description: 変更された(業務)データエンティティの名前です。
      type: string
      example: 'sales_order.order'
    data_op:
      type: string
      enum: ['C', 'U', 'D', 'S']
      description: |
        エンティティに対して実行した操作の種類です。
        - C: エンティティの新規作成
        - U: エンティティの更新
        - D: エンティティの削除
        - S: ある時点でのエンティティのスナップショット作成
----

データ更新イベントカテゴリは、構造的に汎用イベントカテゴリとは異なります。
`data` フィールドでカスタムペイロードを定義し、 `data_type` にデータ変更に関する
固有の情報を定義します。
例えば次の例では、 `a` と `b` のフィールドは、 `data` フィールドの内側に
おかれたカスタムペイロードの一部です。

データ更新イベントカテゴリの使い方の指針は、以下のガイドラインも参照ください。

* <<205>>
* <<202>>
* <<204>>

[#event-metadata]

汎用カテゴリもデータ更新イベントカテゴリも、 _メタデータ_ に関しては、
共通の構造をもちます。
メタデータの構造は、Open APIスキーマオブジェクトとして以下のように表せます。

[source,yaml]
----
EventMetadata:
  type: object
  description: |
    Carries metadata for an Event along with common fields. The required
    fields are those expected to be sent by the producer, other fields may be
    added by intermediaries such as publish/subscribe broker.
  required:
    - eid
    - occurred_at
  properties:
    eid:
      description: このイベントの識別子です。
      type: string
      format: uuid
      example: '105a76d8-db49-4144-ace7-e683e8f4ba46'
    event_type:
      description: このイベントのEventTypeの名前です
      type: string
      example: 'example.important-business-event'
    occurred_at:
      description: イベントが送信者によって作成された日時
      type: string
      format: date-time
      example: '1996-12-19T16:39:57-08:00'
    received_at:
      description: |
        ブローカのような仲介者にイベントが届いた日時
      type: string
      readOnly: true
      format: date-time
      example: '1996-12-19T16:39:57-08:00'
    version:
      description: |
        このイベントをバリデーションするのに使われるスキーマのバージョンです。
        これは仲介者によって。This may be enriched upon reception by intermediaries.
        この文字列にはセマンティックバージョニングが使われます。
      type: string
      readOnly: true
    parent_eids:
      description: |
        このイベントが生成される原因となったイベントの識別子です。
        イベント送信者がセットします。
      type: array
      items:
        type: string
        format: uuid
      example: '105a76d8-db49-4144-ace7-e683e8f4ba46'
    flow_id:
      description: |
        (X-Flow-Id HTTPヘッダと対応した) このイベントのflow-idです。
      type: string
      example: 'JAh6xH4OQhCJ9PutIV_RYw'
    partition:
      description: |
        このイベントに割り当てられたパーティションを示します。
        あるイベント型のイベントがパーティションに分割されるシステムで使わます。
      type: string
      example: '0'
----

イベントの送信者と、その最終的な受信者の間で、イベントのバリデーションやイベントの
<<event-metadata,metadata>> を充実させるような操作がなされる可能性があることに注意してください。
例えばNakadiのようなブローカは、バリデーションしたり、任意のフィールドを追加したり、
あるフィールドが与えられていなければ、デフォルト値などをセットしたりできます。
そんなシステムがどう動くかは、このガイドラインのスコープ外ですが、イベント送信者と受信者が、
それを扱わなくてはならないので、追加の情報をドキュメントに書いておくべきです。

[#199]
== {MUST} イベントに有用な業務リソースを定義していることを保証する

イベントは業務プロセス/データの分析・モニタリングを含む他のサービスによって
使われることを想定しています。
したがって、サービスドメインのために定義されたリソースや業務プロセスに基づくものであるべきだし、
業務の自然なライフサイクルに即したものであるべきです (<<139>> および <<140>> を参照)。

イベント型やトピックスを大量に作るのはコストがかかるので、複数のユースケースで使えるような
抽象的/汎用的なイベント型を定義するようにしましょう。そして、明確なニーズがない限りは
イベント型を公開するのは避けましょう。

[#200]
== {MUST} イベントにカスタマの個人情報データを載せてはならない

APIの権限スコープと同様に、近い将来イベント型の権限もOAuthトークンで渡せるようになるでしょう。
それまでは、次の注意事項にしたがうようにしてください。

* (Eメールアドレス、電話番号などの)機微な情報は、厳重なアクセス管理とデータ保護がされなければならない
* イベント型のオーナーは、それが必須か任意かによらず、機微な情報を公開 *してはならない* 。
例えばイベントが(他のAPIと同様) 注文配送の送付先住所のような個人情報を扱う必要が時々あるが、
これは問題ない。

[#201]
== {MUST} 業務プロセスのステップと到達点を通知するために、汎用イベントカテゴリを使う

イベントが業務プロセスにおけるステップを表現したものであるならば、
イベント型は汎用イベントカテゴリのものでなくてはならなりません。

単一の業務プロセスにまつわるすべてのイベントは、次のルールを遵守してください。

* 業務イベントには、業務プロセスの実行にあたり全てのイベントを効率的に集約するために、
特定の識別子フィールド (業務プロセスID または "bp-id") を含める。 flow-idと同様。
* 業務イベントには業務プロセス実行にあたり、正しくイベントを順序付けするための方法を含める。
(時系列性を信頼して良い正確なタイムスタンプのような) 単調増加する値が得られないような
分散環境においては、`parent_eids` データがイベント間の因果関係を表すものとて使える。
* 業務イベントは特定のステップ/到達点にて、業務プロセスの実行に対して、新しい情報のみ
を含んでいるべきである。
* それぞれの業務プロセスシーケンスは、すべての関連するコンテキスト情報を含んだ
業務イベントによって開始されるべきである。
* 業務イベントは、サービスによって確実に送信されなければならない。

単一のイベント型を使い、状態フィールドで特定のステップを表現する業務業務プロセスのイベント
すべてを公開するのがよいのかどうか、
各ステップを表現するために複数のイベント型を使ったほうがよいのかどうか、
現時点では何がベストプラクティスか私たちには分かりません。
与えられた業務プロセスについて、今は私たちはそれぞれの選択肢を評価し、その1つにこだわって
みようと、そう考えているのです。

[#202]
== {MUST} 変化を通知するためにデータ変更イベントを使う

データの作成、更新、削除を表すイベントを送出するとき、イベント型はデータ変更イベントカテゴリ
のものでなくてはなりません。

* 変更イベントは、あるエンティティに関連するすべてのイベントを集約できるよう
変更されたエンティティを識別できなくてはなりません。
* 変更イベントは <<203>>
* 変更イベントはサービスによって確実に送信されなければならない。

[#203]
== {SHOULD} 明示的にイベントを順序付けする方法を与える

エラーが発生した場合、イベントストリームを再構成したり、
ストリームの中での位置からイベントを再現したりすることを、イベント受信者に要求することが
あります。
それゆえにイベントは、部分的な発生順を再現できる方法を含んで _いなければなりません_ 。

これは、(例えばデータベースで作成する) エンティティのバージョンやメッセージカウンタを
使って実現します。これらは厳密かつ単調に増加する値を使います。

システムタイムスタンプを使うのはあまり良い選択ではありません。分散システムにおいて
正確な時刻同期は困難だし、2つのイベントが同じマイクロ秒で発生するかもしれないし、
またシステムクロックは、時刻合わせのドリフトやうるう秒で前後する可能性もあるためです。
もしイベントの順番を表すのにシステムタイムスタンプを使えば、設計したイベント順がこれらの影響で
混乱を来さないことを注意深く保証しなければなりません。

分散環境でデータ構造によってこの問題を解消する (
https://en.wikipedia.org/wiki/Conflict-free_replicated_data_type[CRDTs],
https://en.wikipedia.org/wiki/Logical_clock[logical clocks] や
https://en.wikipedia.org/wiki/Vector_clock[vector clocks] のような)
仕組みはこのガイドラインのスコープ外であることに *注意* してください。

[#204]
== {SHOULD} データ変更イベントにはハッシュパーティション戦略を使う

`hash` パーティション戦略は、イベントが追加されるべき論理パーティションを
計算するためのインプットとして使われるフィールドを、イベント送信者は定義できます。
イベントエンティティの順序をパーティションローカルで決めれる間は、スループットを
スケールできるようになります。

`hash` オプションは、特にデータ変更に有用です。それによって、あるエンティティに関連するすべてのイベントを、
パーティションへ一貫性をもって割り当てることができるし、そのエンティティに関する
順序付けされたイベントストリームを提供できるようになるからです。
これは各パーティションが全順序性をもつならば、パーティションをまたいだ順序が
サポートするシステムでは保証されないので、パーティションをまたいで送信されたイベントは、
サーバに到着したのとは異なる順序で、イベント受信者に見える可能性があることを示しています。

`hash` 戦略を使うとき、ほとんどすべての場合、パーティションキーは変更されるエンティティを
表すものであり、 `eid`フィールドやタイムスタンプのようなイベント毎に付与されたり、
変更識別子だったりするものではありません。
これによって、データの変更イベントが、同じエンティティでは同じパーティションに入ることが保証され、
クライアントは効率的にイベントを受信できるようになる。

データ変更イベントが、送信者側が定義したり、ランダムに選択したりと、
独自のパーティション戦略をもつ例外的な場合があるかもしれませんが、
一般的にいって、 `ハッシュ` が正しい選択しです。
ここでのガイドラインは "should" ですが、"すごくイカした理由がない限りは、must" と読み替えてください。

[#205]
== {SHOULD} データ変更イベントがAPI表現にマッチすることを保証する

データ変更イベントのエンティティ表現は、REST APIの表現と対応しているべきです。

あるサービスにとって最小限の構造しか持たないようにすることに価値があります。
そうすれば、サービスの利用者にとってはより少ない表現しか使わずにすむし、
サービスオーナーにとっては、保守しなくてはならないAPIが少なくてすみます。
特に、そのドメインに関連していて、実装やローカルの詳細から切り離され抽象化されたイベントのみ
公開するようにすべきです。
システム内で起こるすべての変更を反映する必要はありません。

APIリソース表現と直接関係のないデータ変更イベントを定義する意義がある場合もあります。例えば次のような場合です。

* APIリソース表現がデータストア表現とかなり乖離があるが、物理的なデータの方がデータ統合のための
確実に処理するのがより簡単である。
* 集約されたデータの送信。例えば個々のエンティティへの変更データが、
APIのために定義されたものよりも、粒度のあらい表現を含んだイベントが送出されるかもしれない。
* マッチングアルゴリズムのような計算結果や大量に生成されたデータで、
サービスによってエンティティとして保存しないかもしれないイベント。

[#206]
== {MUST} イベントの権限はAPIの権限に対応しなければならない

リソースがREST APIを通じて同期的に読み取りアクセスでき、イベントを通じて非同期で読み取りアクセスできると
すると、同じ読み取り権限が適用されていなければならない。
私たちはデータを保護したいのあって、データのアクセス方法を保護したい訳ではないのだから。

[#207]
== {MUST} イベント型のオーナーを明示する

イベント定義は、所有者をハッキリさせておかなければなりません。EventTypeの `owning_application` で明示します。

EventTypeのオーナーでその定義に責任をもつのは、1つの送信アプリケーションであることが
多いですが、そのオーナは同種のイベントを送信する複数のサービスの1つであってもよいです。

[#208]
== {MUST} 全体のガイドラインにしたがってイベントのペイロードを定義する

イベントは他のAPIデータやAPIガイドラインと整合性のとれたものでなくてはなりません。

<<introduction>> で表したすべてが、サービス間でデータをやり取りするイベントに適用されます。
APIと同様にイベントは、私たちのシステムが何をしているのかを表現するための責務を果たし、
高品質に設計された有用なイベントが、私たちの新しく面白いプロダクトやサービス開発を支えるのです。

イベントが他の種類のデータと異なるのは、非同期のpub-subメッセージングのように、
データの伝達に使われるところにあります。だからといって、
例えば検索リクエストやページ分割されたフィードのように、REST APIを使うような
ところでイベントが使えない訳ではありません。
サービスのREST APIのために作ったモデルを、イベントでもベースとすることになるでしょう。

次のガイドラインの章がイベントにも適用されます。

* <<general-guidelines>>
* <<api-naming>>
* <<data-formats>>
* <<common-data-types>>
* <<hypermedia>>

[#209]
== {MUST} イベントのために後方互換性を維持する

イベントの変更は項目追加や後方互換のある変更を基本としなければなりません。
これは <<compatibility>> ガイドラインの「Must: 後方互換性を崩してはならない」
にしたがうものです。

イベントの文脈では、互換性の事情は複雑です。
イベントの送信者も受信者も高度に非同期化されていて、
RESTのクライアント/サーバでは適用できていた content-negotiation を用いた
テクニックは使えないためです。
これは後方互換維持のためのより高いハードルを、受信者側に課すことになります。
要求に応じてバージョニングしたメディアタイプを返すということが出来ないためです。

イベントスキーマでは、受信者側から見たときに、以下のものは後方互換性があると
考えられます。

* JSONオブジェクトへの新しい任意のフィールドの追加
* フィールドの並び順の変更 (オブジェクトにおけるフィールドの並びは任意である)
* 配列内の同じ型の値の並び順変更
* 任意のフィールドの削除
* 列挙型の個々の値の削除

また、受信者側から見たときに、以下のものは後方互換性がないと考えられます。

* JSONオブジェクトから必須のフィールドの削除
* フィールドのデフォルト値の変更
* フィールド、オブジェクト、列挙型、配列の型の変更
* 配列内の異なる型の値の並び順変更 (こういった配列はタプルとして知られている)
* 既存のフィールドを再定義した新しい任意のフィールドの追加 (共起制限として知られている)
* 列挙型への値の追加 (<<112,`x-extensible-enum`>> はJSONスキーマでは使えないことに注意)

[#210]
== {SHOULD} イベント型定義では `additionalProperties` を避ける

イベント型のスキーマでは、スキーマの成長をサポートするため `additionalProperties` の使用を避けるべきです。

イベントはpub-subシステムによって中継されることが多く、共通的にログがとられたり、
後で読み込むためにストレージに保存されたりします。
特に受信者と送信者双方で使われるスキーマは、時間とともに変化していきます。
結果として、クライアント・サーバ型のAPIではあまり起こらなかった互換性と拡張性の問題が、
イベントの設計では重要かつふつうに考えなきゃならいことになってくるのです。
イベントスキーマの成長を可能にするため、ガイドラインは次の点を推奨します。

* イベント送信者は後方互換性を維持し安全にスキーマを修正できるよう、
`additionalProperties` を `true` (つまりワイルドカードの拡張ポイントを意味する) で宣言 *してはならない* 。
かわりに新しい任意のフィールドを定義し、安これらのフィールドを公開する前に、スキーマを更新しなければならない。
* イベント受信者は自分が処理できないフィールドは無視し、エラーを発生させては *いけない* 。
これは送信者によって指定された新しい定義を含むものよりも、古いイベントスキーマが適用されたイベントを
処理しなければならないときに発生する。

上記制約は、イベント型スキーマの将来のリビジョンで、フィールドが追加できないことを意味してはいません。
イベント型の新しいスキーマが、イベント送信前に前にまずフィールドを定義していれば、
互換性のある追加で許されたオペレーションです。
同じ順番で、受信者はAPIクライアントと同様に、スキーマのコピーに情報のないフィールドを無視しなければなりません。
すなわち、 イベント型スキーマが拡張に対して閉じていたとしても
`additionalProperties` フィールドがないことを扱うことができないのです。

_フィールド再定義 _ の問題を避けるため、イベント送信者にイベント送信する前に、
フィールドを定義すること要求します。
これはイベント送信者が、既に送出された異なる型のイベントにフィールドを定義したり、未定義のフィールドの型を変更したりしている場合です。
どちらも、 `additionalProperties` を使わないことで防げます。

`additionalProperties` の使用についてのガイドラインは、 <<compatibility>>
の章のルール <<111>> を参照ください。

[#211]
== {MUST} ユニークなイベント識別子を使う

イベントの `eid` (イベント識別子)の値は、ユニークでなくてはなりません。

`eid` プロパティは、イベントの標準の <<event-metadata,metadata>> の一部であり、
イベントに識別子を与えるものです。
送信クライアントは、イベント送出時にこれを生成し、所有アプリケーションの範囲で
ユニーク性を保証しなければなりません。
特に、あるイベント型のストリームをともなうイベントは、ユニークな識別子はマストです。
これはイベント受信者が、 `eid` をイベントがユニークであるとして処理したり、
冪等性のチェックに使ったりするためです。

イベントを受信するシステムが `eid` のユニーク性のチェックすることは任意であるので、
送信者側がイベント識別子のユニーク性を保証する責務があることに注意しましょう。
イベントのユニーク識別子を生成する単純な方法は、UUIDを使うことです。

[#212]
== {SHOULD} 冪等な順不同の処理を設計する

<<149,冪等>> で順不同の処理をするものとしてイベントを設計しておくと、
非常にレジリエントなシステムとなります。もしイベントの処理に失敗しても、
送信者と受信者は、処理を一時停止したり、処理結果の整合性を崩すことなく、
イベント処理をスキップしたりディレイさせたりリトライしたりできます。

このように処理順を自由にするには、冪等で順不同な処理設計を明示的にやる必要があります。
イベントが元の順序を推測するのに十分な情報を含むようにしたり、業務ドメインが
順序性によらないような方法で設計するようにします。

データ変更イベントと似た共通の例として、冪等で順不同な処理は、次の情報を送る
ことによって達成されます。

* プロセス/リソース/エンティティの識別子
* <<203,単調増加する順序付けられたキー>>
* 変更後のプロセス/リソースの状態

受信側が現在の状態にだけ関心があるのであれば、各リソースの最新イベントよりも古いものは
無視できます。
受信側がリソースの履歴にも関心があるのであれば、(部分的にでも) 順序性のある一連のイベントを
再生成するために、順番に並んだキーを使います。

[#213]
== {MUST} イベント型の名前は命名規約にしたがう

イベント型の名前は、次に示すとおり <<219, オーディエンス>> に依存した機能本位の命名に準拠しなければなりません。
(またはそうするべきです。 <<223>> に詳細と定義があります)

[source,bnf]
----
<event-type-name>       ::= <functional-event-name> | <application-event-name>

<functional-event-name> ::= <functional-name>.<event-name>

<event-name>            ::= [a-z][a-z0-9-]* -- 自由なイベント名 (機能を表す名前)
----

次のアプリケーション固有のレガシーな規約は、 <<223, 内部>> イベント型名に *のみ*
適用するようにしてください。

[source,bnf]
----
<application-event-name> ::= [<organization-id>.]<application-id>.<event-name>
<organization-id>  ::= [a-z][a-z0-9-]* -- 組織の識別子 (例えばチームIDのような)
<application-id>   ::= [a-z][a-z0-9-]* -- アプリケーションの識別子
----

**注意:** 同じエンティティをデータ変更イベントとRESTful APIの両方で扱うときは、
一貫性のある名前を使うようにしましょう。

[#214]
== {MUST} 重複したイベントに備える

イベントの受け手は、重複したイベントを正しく処理できなくてはなりません。

大抵のメッセージブローカとデータストリーミングシステムは、"at-least-once"配信をサポートしています。
これはある特定のイベントが、必ず1回以上は受け手に届くことを保証するものです。
別の状況でも、重複したイベントが発生する可能性があります。

例えば、イベントの送信者が(ネットワークの問題によって) 受け手に届かなかったような
状況で発生します。この場合、送信者は同じイベントの再送を試みます。
こうしてイベントバスに受信者が処理すべき同一のイベントが2つ存在することになります。
同じ状態は受信者側でも起こります: イベントは正しく処理したが、その処理が確認出来ない場合です。
