[[json-guidelines]]
= JSONガイドライン

ZalandoにおいてJSONデータを定義するのに推奨されるガイドラインです。
JSONとは、ここでは {RFC-7159}[RFC 7159] ({RFC-4627}[RFC 4627] のアップデート)を指します。
"application/json"のメディアタイプとAPIで定義されたカスタムのJSONメディアタイプをもちます。
このガイドラインでは、Zalandoの用語やサービスの用例をもつJSONデータを使って、具体的なケースを示します。

最初のいくつかはプロパティ名についてのガイドラインであり、
後半は値についてのガイドラインになります。

[#118]
== {MUST} プロパティ名はASCIIスネークケースでなければならない (キャメルケースは使わない): `[a-z_][a-z_0-9]\*$`

プロパティ名は、ASCII文字列という制限があります。最初の一文字はアルファベットまたはアンダースコアで、
それに続く文字は、アルファベットまたはアンダースコア、数字のいずれかでなくてはなりません。

(`\_links`  のようなキーワードのみ、 `\_` から始まるプロパティ名とすることを推奨します)

理念: 確立された標準は存在しませんが、多くの有名インターネット企業は、スネークケースを好みます。
GitHub, Stack Exchange, Twitterなど。一方でGoogleやAmazonは、- だけでなくキャメルケースも
使っています。同じところからくるJSONが一貫したルック・アンド・フィールとなるように設計するのは
必要不可欠なことです。

[#240]
== {MUST} enumの値は、UPPER_SNAKE_CASE形式で宣言する

Enumの値 (`enum` または {x-extensible-enum}で使われる) は、大文字のスネークケース形式を一貫して使う必要があります。 `VALUE` や `YET_ANOTHER_VALUE` のように。このすると、プロパティや他の要素との区別がハッキリつくためです。

[#216]
== {SHOULD} Mapは `additionalProperties` を使って定義する

ここで「map」は、文字列のキーから他の型へのマッピングを意味します。
JSONにおいてこれはオブジェクトとして表現されます。キーと値のペアはプロパティ名とプロパティの値によって
表現されます。
OpenAPIスキーマにおいては(JSONスキーマにおいても同様)、それらはadditionalPropertiesを使って
表現すべきとされます。そのようなオフジェクトは他に定義されたプロパティは持ちません。

mapのキーは、命名<<118,ルール 118>>の意味ではプロパティ名とみなしませんので、ドメイン固有のフォーマットに
したがうようにします。
ドキュメントにはmapオブジェクトのスキーマの詳細に、これを記述するようにしてください。
これはそのようなmapの例です。(`transactions` プロパティがそれにあたります)


```yaml
components:
  schemas:
    Message:
      description:
        いくつかの言語に翻訳したメッセージ
      type: object
      properties:
        message_key:
          type: string
          description: メッセージのキー
        translations:
          description:
            このメッセージをいくつかの言語に翻訳したもの。
            キーは https://tools.ietf.org/html/bcp47[BCP-47 言語タグ] である。
          type: object
          additionalProperties:
            type: string
            description:
              キーによって識別された言語に、このメッセージを翻訳したもの
```

実際のJSONオブジェクトは次のようなものです。

```json
{ "message_key": "color",
  "translations": {
    "de": "Farbe",
    "en-US": "color",
    "en-GB": "colour",
    "eo": "koloro",
    "nl": "kleur"
  }
}
```

[#120]
== {SHOULD} Arrayの名前は複数形にする

複数の値をもつArrayのプロパティ名は複数形にします。これはオブジェクトの名前は単数形にすべきということも暗に示しています。

[#122]
== {MUST} Booleanのプロパティに `null` を使わない。

booleanとして設計されたJSONプロパティは、スキーマ上nullであってはなりません。
booleanはtrueとfalseの2つの値をもった列挙型です。もしnull値をもちたいことがあれば、
booleanの代わりに列挙型を使うことを強く奨めます。
例えばaccepted_terms_and_conditionsがtrueまたはfalseをもつとき、
これはyes/no/unknownの値をもったterms_and_conditionsに置き換えることができます。

[#123]
== {MUST} `null` とプロパティ自体が無いことを同一セマンティクスで使わない

Open API 3.x では、プロパティが無い(`{}`)かもしれないことと、`null` (`{"example":null}`)を表すのに、`required`  と `nullable`  を付けることができます。
もし、あるプロパティが `required` でなく `nullable`  だと定義されていたら(<<required-nullable-row-2, 下表の2行目>>のように)、このルールは、双方を正確に同じ方法で扱えるようにしなければなりません。

次の表は、すべての組み合わせとそれが有効かどうかを示します。

[cols=",,,",options="header",]
|===========================================
| {CODE-START}required{CODE-END} | {CODE-START}nullable{CODE-END}
| {CODE-START}{}{CODE-END} | {CODE-START}{"example":null}{CODE-END}
| `true`  |`true`   | {NO}  | {YES}
| `false` | `true`  | {YES} | {YES} [[required-nullable-row-2]]
| `true`  |`false`  | {NO}  | {NO}
| `false` |`false`  | {YES} | {NO}
|===========================================

APIの設計者や実装者は、どちらの場合も異なる意味を割り当てたくなるかもしれませんが、表現力が高いことよりも、クライアントがその微妙な違いを理解せず誤って実装してしまうリスクの方がはるかに高いと考えられるので、私たちはこの選択肢には反対です。

例えばミーティングのように、異なるユーザがスケジュールを調整できるようなAPIでは、各ユーザが `選択` しなければならない選択肢をリソースとできます。 _undecided_ と _decided_ の違いは、それぞれ _absent_ と `null` としてモデル化できる。 `null` の場合は、https://en.wikipedia.org/wiki/Null_object_pattern[Null object] (例えば、`{"id":"42"}` に対しての`{}` のように)として表すのが安全です。

さらに多くの主要なライブラリは、 `null` / absent パターンをほとんどサポートしていないか、まったくサポートしてないかという状態です。(https://stackoverflow.com/questions/48465005/gson-distinguish-null-value-field-and-missing-field[Gson],
https://github.com/square/moshi#borrows-from-gson[Moshi],
https://github.com/FasterXML/jackson-databind/issues/578[Jackson],
https://developer.ibm.com/articles/j-javaee8-json-binding-3/[JSON-B])
特に、強い型付けを持つ言語では、第3の状態を表現するためには新しい複合型が必要なため、この問題に頭を悩まします。Nullable `Option` / `Optional` / `Maybe` 型を使うことができますが、これらの型のNullableな参照を持つことは、その型の目的と完全に矛盾してしまいます。

このルールの唯一の例外はJSON Merge Patch {RFC-7396}[RFC 7396])で、これは `null` を使ってプロパティの削除を明示的に示しますが、存在しないプロパティは無視されます。つまり変更されません。

[#124]
== {SHOULD} 空のArray値はnullにはしない

Arrayが空であることは `[]` として曖昧さなく表現できます。

[#125]
== {SHOULD} 列挙型はStringとして表現する

Stringは列挙型で設計された値を表現するには妥当な型です。

[#235]
== {SHOULD} 日付/日時のプロパティには `\_at` をサフィックスとして付ける

日付と日時のプロパティは `\_at` で終わるようにすべきです。よく似た名前のbooleanプロパティと区別できるようになります。

- {created_at} rather than {created},
- {modified_at} rather than {modified},
- `occurred_at` rather than `occurred`, and
- `returned_at` rather than `returned`.

**注意:** {created} と {modified} はガイドラインの以前のバージョンで言及されていました。したがって、このルールより前のAPIでも引き続き受容されます。

[#126]
== {SHOULD} 日付型のプロパティ値はRFC 3339に準拠する

{RFC-3339}#section-5.6[RFC 3339]
で定義された日付と時刻のフォーマットを使いましょう。

* "date"には `年 "-" 月 "-" 日` を使う。例: `2015-05-28`
* "date-time"には `年-月-日 "T" 時:分:秒`を使う, 例: `2015-05-28T14:07:17Z`

https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#data-types[OpenAPI
フォーマット] の"date-time"はRFCの"date-time"に相当し、`2015-05-28`のして表されるOpen APIフォーマットの
"date"は、RFCの"full-date"に相当します。
どちらもspecific profilesで、国際標準 http://en.wikipedia.org/wiki/ISO_8601[ISO 8601] のサブセットです。

(リクエストとレスポンスの両方で) ゾーンオフセットが使われる可能性があります。
これも標準で定義されているものです。
しかし、私たちは日付に関しては、オフセットなしのUTCを使うよう制限を設けることを
推奨しています。`2015-05-28T14:07:17+00:00` ではなく、`2015-05-28T14:07:17Z` のように。
これはゾーンオフセットは理解が難しく、正しく扱えないことがよくあることを経験上学んだので、そうしています。
ゾーンオフセットはサマータイムを含むローカルタイムとは異なることに注意してください。
日時のローカライズは、必要ならユーザインタフェースを提供するサービスによってなされるべきです。
保存するときは、すべての日時データはゾーンオフセットなしのUTCで保存します。

時々、数値タイムスタンプで日時を表すデータを見かけますが、
これは精度に関しての解釈の問題を引き起こします。
例えば1460062925というタイムスタンプの表現は、1460062925000 なのか 1460062925.000 なのか
判別できません。日時文字列は冗長でパースが必要ですが、この曖昧さを避けるために必要なことなのです。

[#127]
== {MAY} 期間(duration)と時間間隔(interval)はISO8601に準拠する

期間と時間間隔の設計は、{ISO-8601}[ISO 8601]で推奨されている形式の文字列を使います。
(期間については {RFC-3339}#appendix-A[付録A RFC 3339に文法が含まれます] )
