[[pagination]]
= ページネーション

[#159]
== {MUST} ページネーションをサポートする

リストデータへのアクセスは、クライアントサイドの一括処理と繰り返し操作のために、ページネーションをサポートしなければなりません。これは数百エントリ以上の(になる可能性のある)リストすべてにあてはまります。

2つのページネーションのテクニックがあります。

* https://developer.infoconnect.com/paging-results[Limit/Offsetベース]: 最初のページエントリをオフセット数値で特定する
* https://dev.twitter.com/overview/api/cursoring[cursor/limitベース] — またの名をキーベース — ページネーション: 単一のキー要素で最初のページエントリを特定する
(https://developers.facebook.com/docs/graph-api/using-graph-api/v2.4#paging[Facebookのガイド]も見てください)

ページネーションの技術的概念は、問題がユーザエクスペリエンスと結びついていることも考慮しなければなりません。
この https://www.smashingmagazine.com/2016/03/pagination-infinite-scrolling-load-more-buttons/[記事] で述べられているとおり、
特定のページへのジャンプは、「前へ」「次へ」のページリンク(<<161>>参照)よりもあまり使われることはありません。
それがオフセットベースのページネーションよりも、カーソルベースのページネーションを指向したい理由です。

**注意:** ページネーションの一貫したルックアンドフィールを提供するため、<<137>>で定義された共通のクエリパラメータ名を使わなければなりません。

[#160]
== {SHOULD} オフセットベースのページネーションを避け、カーソルベースのページネーションを使う

カーソルベースのページネーションは、オフセットベースのページネーションと比較すると、
いい感じでより効率的です。
データ量が多くなってきた時やNoSQLデータベースのストレージでは特に顕著です。

カーソルベースのページネーションを選択する前に、次のトレードオフを検討しておきましょう。

* 使い勝手とフレームワークのサポート
** オフセットベースのページネーションはカーソルベースよりもよく知られており、フレームワークがサポートしていたり、APIクライアントで簡単に使えたりする
* ユースケース: とあるページへジャンプする
** (100ページ中の51ページのように) 特定のページにジャンプするようなユースケースは、カーソルベースでは実現できない
* データの変更は結果セットのページに異常を引き起こす可能性がある
** オフセットベースのページネーションは、ページ遷移の間に更新や削除がされると、結果の重複やロストを引き起こす可能性がある。
** カーソルベースのページネーションを使うときは、2つのページを取得する間にカーソルの指し示すエンティティの削除がおこなわれると、ページングを継続することはできない。
* パフォーマンスの考慮 - オフセットベースのページネーションを使ったサーバ処理は効率的に実行するのが難しい
** データベースのメインメモリにデータが存在しない場合は特に、コストの高い処理になる。
** 共有データベースかNoSQLか?
* カーソルベースのナビゲーションは、結果の総件数が必要だったり、後方へのページネーションをサポートする必要がある場合には実現できないかもしれません。

ページネーションのために使われる{cursor}は、ページへのOpaqueポインタで、クライアントが *検査* したり *構築* したりしてはならない。通常は安全にコレクションを再作成できるように、ページの位置、すなわち、最初または最後のページ要素の識別子、ページネーションの方向、適用されたクエリフィルタを(暗号化)エンコードしたものです。{cursor}は次のように定義されます。

[source,yaml]
----
Cursor:
  type: object
  properties: 
    position:
      description: >
        Object containing the identifier(s) pointing to the entity that is
        defining the collection resource page - normally the position is
        represented by the first or the last page element.
      type: object
      properties: ...

    direction:
      description: >
        The pagination direction that is defining which elements to choose
        from the collection resource starting from the page position.
      type: string
      enum: [ ASC, DESC ]

    query:
      description: >
        Object containing the query filters applied to create the collection
        resource that is represented by this cursor.
      type: object
      properties: ...

    query_hash:
      description: >
        Stable hash calculated over all query filters applied to create the
        collection resource that is represented by this cursor.
      type: string

  required:
    - position
    - direction
----

カーソルベースのページネーションのためのページ情報は、{cursor}の集合で構成する必要があります。{next}に加えて、{prev},{first},{last},{self}を次のようにサポートすることもあります。(<<link-relation-fields>>参照)

[source,json]
----
{
  "cursors": {
    "self": "...",
    "first": "...",
    "prev": "...",
    "next": "...",
    "last": "..."
  },
  "items": [... ]
}
----

*注意:* {cursor}集合のサポートは<<161>>が好まれて、削除されるかもしれません。

さらには以下の文書もあります:

* https://dev.twitter.com/rest/public/timelines[Twitter]
* http://use-the-index-luke.com/no-offset[Use the Index, Luke]
* https://www.citusdata.com/blog/1872-joe-nelson/409-five-ways-paginate-postgres-basic-exotic[Paging
in PostgreSQL]

[#161]
== {SHOULD} 適用可能なところではページネーションリンクを使う

クライアント設計を単純にするために、APIはコレクションのページネーションに適用できるときはいつでも<<165,simplified hypertext controls>>をサポートするべきです。{next}に加えて、{prev}, {first}, {last}, {self}のサポートを含むこともあります。(詳細は<<link-relation-fields>>参照)

このページ内容は{items}を通じて送信さる一方、{query}オブジェクトは次のように適用されたクエリフィルタも含むかもしれません。

[source,json]
----
{
  "self": "http://my-service.zalandoapis.com/resources?cursor=<self-position>",
  "first": "http://my-service.zalandoapis.com/resources?cursor=<first-position>",
  "prev": "http://my-service.zalandoapis.com/resources?cursor=<previous-position>",
  "next": "http://my-service.zalandoapis.com/resources?cursor=<next-position>",
  "last": "http://my-service.zalandoapis.com/resources?cursor=<last-position>",
  "query": {
    "query-param-<1>": ...,
    "query-param-<n>": ...
  },
  "items": [...]
}
----

*注意:* 例えば{GET-with-body}が必要なときのような、複雑な検索リクエストでは、{cursor}はすべてのクエリフィルタをエンコードできないかもしれない。この場合、ページ位置と{cursor}の方向だけをエンコードし、ボディでクエリフィルタを送るのがベストプラクティスでしょう。レスポンスも同様です。ページネーションの順序を守るため、この場合、{cursor}が適用されたすべてのクエリフィルタのハッシュを含ませ、使う前に検証するのがおすすめです。

*注目:* 必要性がない限り、トータル数を与えるのを避けるべきです。多くの場合、全件カウントをサポートすると、システムと性能に多大な影響が出ます。特にデータセットが増大し、リクエストが複雑になった場合は、フィルタによってフルスキャンが実行されます。これはAPIに関連した実装の詳細ですが、サービスの生存よりも、カウント機能が重要なのかよく考えましょう。