[[performance]]
= 性能

[#155]
== {SHOULD} 必要な帯域幅を減らし応答性を改善する

APIはクライアントの必要性に応じて、帯域幅を減らすための仕組みをサポートすべきです。
パブリックなインターネットやテレコミュニケーションネットワークのように、
大きなペイロードをもち高トラフィックなシナリオで使われる(かもしれない)APIに有効です。
低帯域での通信を余儀なくされるモバイルWebアプリのクライアントが使うAPIは、その典型例です。
(Zalandoは'モバイルファースト'な企業なので、この点は心にとどめておきましょう)

共通のテクニックは、

* リクエストとレスポンスのボディの圧縮(<<156>>参照)
* リソース属性のサブセットを取得できるよう、フィールドフィルタをクエリに実装する (<<157>>参照)
* {ETag}と{If-Match}/{If-None-Match}ヘッダを使って、変更のないリソースの再フェッチを避ける (<<182>>参照)
* 巨大なデータコレクションへのインクリメンタルなアクセスのための<<pagination>>
* マスタデータのキャッシュ。すなわち滅多に変更のない、または一切変更されないリソース (<<227>>参照)

それぞれの詳細は以下に示します。

[#156]
== {SHOULD} `gzip` 圧縮を使う

圧縮時間がボトルネックになるほど多くのリクエストを捌かなければならないなど、
特別な理由がない限りは、APIレスポンスのペイロードをgzipで圧縮しましょう。
そうすることでネットワークの転送も速くなるし、フロントエンドの応答性も向上します。

gzip圧縮がサーバペイロードのデフォルトの選択肢ではありますが、サーバは
圧縮しないペイロードもサポートするべきです。クライアントは{Accept-Encoding}リクエストヘッダを
通じてそれをコントロールできます。 {RFC-7231}#section-5.3.4[RFC-7231 Section 5.3.4] も参照してください。
サーバもまた{Content-Encoding}ヘッダを通じて、gzip圧縮が使われていることを明示すべきです。

[#157]
== {SHOULD} フィルタリングによって部分的なレスポンスをサポートする。

ユースケースとペイロードサイズに応じて、返却するエンティティのフィールドの
フィルタリングをサポートすることによって、必要とするネットワーク帯域を大いに減らこすとができるでしょう。
フィールドクエリパラメータを付けることで、クライアントは欲しいデータに応じて、
フィールドのサブセットを決めることができます。
例は https://cloud.google.com/appengine/docs/python/taskqueue/rest/performance#partial-response[Google
AppEngine API's partial response]をみてください。

[[unfiltered]]
=== フィルタなし

[source,http]
----
GET http://api.example.org/users/123 HTTP/1.1

HTTP/1.1 200 OK
Content-Type: application/json

{
  "id": "cddd5e44-dae0-11e5-8c01-63ed66ab2da5",
  "name": "John Doe",
  "address": "1600 Pennsylvania Avenue Northwest, Washington, DC, United States",
  "birthday": "1984-09-13",
  "friends": [{
    "id": "1fb43648-dae1-11e5-aa01-1fbc3abb1cd0",
    "name": "Jane Doe",
    "address": "1600 Pennsylvania Avenue Northwest, Washington, DC, United States",
    "birthday": "1988-04-07"
  }]
}
----

[[filtered]]
=== フィルタあり

[source,http]
----
GET http://api.example.org/users/123?fields=(name,friends(name)) HTTP/1.1

HTTP/1.1 200 OK
Content-Type: application/json

{
  "name": "John Doe",
  "friends": [ {
    "name": "Jane Doe"
  } ]
}
----

{fields}クエリパラメータは、レスポンスのオブジェクトで返されるfieldsを決定するものです。例えば、 `(name)`  は `name` フィールドだけをもつ `users` オブジェクトを返します。また `(name,friends(name))` は、`name` とネストされた `name` フィールドだけもつ `friends` オブジェクトを返します。

Open APIは公式にはパラメータによって異なるオフジェクトを返すスキーマをサポートしていません。フィールドパラメータを定義するときは、次の説明書きを加えておくくことをおすすめします。: `エンドポイントは戻りのオブジェクトのフィールドのフィルタリングをサポートする。 https://opensource.zalando.com/restful-api-guidelines/#157[Rule #157]`

{fields}の値の文法は、次の https://en.wikipedia.org/wiki/Backus%E2%80%93Naur_form[BNF] で定義される

[source,bnf]
----
<fields>            ::= [ <negation> ] <fields_struct>
<fields_struct>     ::= "(" <field_items> ")"
<field_items>       ::= <field> [ "," <field_items> ]
<field>             ::= <field_name> | <fields_substruct>
<fields_substruct>  ::= <field_name> <fields_struct>
<field_name>        ::= <dash_letter_digit> [ <field_name> ] 
<dash_letter_digit> ::= <dash> | <letter> | <digit>
<dash>              ::= "-" | "_"
<letter>            ::= "A" | ... | "Z" | "a" | ... | "z"
<digit>             ::= "0" | ... | "9"
<negation>          ::= "!"
----

**注意:** https://en.wikipedia.org/wiki/Principle_of_least_astonishment[驚き最小化の原則] にしたがい、デフォルト値を使って{fields}パラメータを定義すべきではありません。結果は直感に反するので、API利用者は混乱してしまうからです。

[#158]
== {SHOULD} サブリソースの任意の埋め込みを可能にする

関連するリソースを組み込むこと( _リソース展開_ として知られる)は、リクエスト数を減らすためには
すごくよい手段です。
クライアントが前もって必要な関連リソースを知っている場合は、クライアントからサーバに、
データをEagarにプリフェッチできるよう指示します。
これはサーバで最適化されるのか(例えば、データベースのJOIN)、
一般的な手段(例えば透過的にリソースを差し込むHTTPプロキシ)で実現されるのかは、
実装次第です。

命名に関しては <<137>> を参照ください。例えば埋め込みリソース展開には "embed" を使います。
埋め込みクエリには、前述のフィルタリングと同様の https://en.wikipedia.org/wiki/Backus%E2%80%93Naur_form[BNF] 文法を使うようにしてください。

サブリソースの埋め込みは、例えばある注文がそのサブリソース (/order/{orderId}/items)
として注文品目をもつような場合には、以下のようにみえます。

[source,http]
----
GET /order/123?embed=(items) HTTP/1.1

{
  "id": "123",
  "_embedded": {
    "items": [
      {
        "position": 1,
        "sku": "1234-ABCD-7890",
        "price": {
          "amount": 71.99,
          "currency": "EUR"
        }
      }
    ]
  }
}
----

[#227]
== {MUST} キャッシュ可能な `GET`, `HEAD`, `POST` エンドポイントをドキュメント化する

キャッシュは多くのことを考慮しなければなりません。例えば、一般的なレスポンス情報の<<cacheable,キャッシュ可能性>>や、SSLを使ったエンドポイントを保護するガイドライン、リソースの更新とキャッシュ無効化のルール、複数のAPI利用者の存在などがあります。結果として、キャッシュは最良でも複雑(一貫性の観点などから)、最悪の場合は逆に非効率的なものになります。

頻繁に使用され、そのためにレート制限されたマスタデータサービス、すなわち、作成後にほとんどあるいは全く更新されないデータなど、サービスがそれ自体を保護することをサポートしない限り、クライアントサイドでの、また透過的なWebキャッシュを使うことは避けるべきです。

デフォルトでは、API提供者と利用者は常に{Cache-Control}ヘッダを{Cache-Control-no-store}にセットすべきであり、もし{Cache-Control}が設定されていなければ、同じく{Cache-Control-no-store}がセットされたものとして扱うべきです。

**注意:** このデフォルト設定をドキュメント化する必要はありません。ただし、フレームワークがデフォルトでこのヘッダの値を付加していることを確認するか、あるいは手動で(例えば下記のようなSping Securityのベストプラクティスを使って) これを確認してください。このデフォルトから外れた設定は、十分なドキュメント化が必要です。

[source,http]
----
Cache-Control: no-cache, no-store, must-revalidate, max-age=0
----

もしサービスが本当にキャッシュのサポートを必要とするなら、以下のルールにしたがってください。

* <<cacheable,キャッシュ可能>>な{GET}, {HEAD}, {POST}のエンドポイントはすべて、レスポンスに{Cache-Control}, {Vary}, {ETag}ヘッダのサポートを宣言することによってドキュメント化する。 *注意:* {Expires}ヘッダは、キャッシュ生存期間の冗長で曖昧な定義を避けるため、定義してはならない。これらのヘッダのデフォルト文書を以下に示す。
* {Cache-Control}と{Vary}を使って正しくキャッシュ境界、すなわち生存期間やキャッシュ制約を定義し、キャッシュのサポートを明記しよう。以下でベストプラクティスを示す。
* [[cache-support-patterns]]キャッシュをウォームアップし、更新するのに効率的な方法を提供する。つまり、以下のようなものである。
** 一般的には、<<182, `If-Match` / `If-None-Match`  ヘッダと一緒に `ETag` >> を全ての <<cacheable, キャッシュ可能な>> エンドポイントでサポートする。
** 巨大なデータには、{HEAD}リクエストや{If-None-Match}ヘッダとともに{GET}を使う効率的なリクエストで、更新のチェックをする。
** 小さなデータセットでは、{ETag}をサポートした{GET}リクエストを提供し、{If-Non-Match}付きの{HEAD}リクエストや{GET}リクエストで更新のチェックをする。
** 中くらいのサイズのデータセットは、<<pagination>>とともに{ETag}をサポートする{GET}リクエストと、与えられた{entity-tag}以降の変更に対してレスポンスを制限する{GET}リクエストをフィルタリングするための{entity-tag}を使う。 *注意:* これは一般的なクライアントやHTTPレイヤでのプロキシキャッシュではサポートされない。

*ヒント:* キャッシュを適切にサポートするために、失敗した{HEAD}リクエストまたは{GET}リクエストでは、{304}ではなく<<182, `If-None-Match: <entity-tag>`>>を指定したコンテンツなしの{412}を返す必要があります。

[source,yaml]
----
components:
  headers:
  - Cache-Control:
      description: |
        The RFC 7234 Cache-Control header field is providing directives to
        control how proxies and clients are allowed to cache responses results
        for performance. Clients and proxies are free to not support caching of
        results, however if they do, they must obey all directives mentioned in
        [RFC-7234 Section 5.2.2](https://tools.ietf.org/html/rfc7234) to the
        word.

        In case of caching, the directive provides the scope of the cache
        entry, i.e. only for the original user (private) or shared between all
        users (public), the lifetime of the cache entry in seconds (max-age),
        and the strategy how to handle a stale cache entry (must-revalidate).
        Please note, that the lifetime and validation directives for shared
        caches are different (s-maxage, proxy-revalidate).

      type: string
      required: false
      example: "private, must-revalidate, max-age=300"

  - Vary:
      description: |
        The RFC 7231 Vary header field in a response defines which parts of
        a request message, aside the target URL and HTTP method, might have
        influenced the response. A client or proxy cache must respect this
        information, to ensure that it delivers the correct cache entry (see
        [RFC-7231 Section
        7.1.4](https://tools.ietf.org/html/rfc7231#section-7.1.4)).

      type: string
      required: false
      example: "accept-encoding, accept-language"
----

*ヒント:* {ETag}ソースには<<182>>を参照してください。

{Cache-Control}のためのデフォルト設定は、標準の<<104,OAuth認証>>を持つエンドポイントに対する
`private` ディレクティブと、クライアントが古いキャッシュエントリを使わないようにするための
`must-revalidate` ディレクティブが含まれている必要があります。
最後に `max-age` ディレクティブは、マスタデータの変更率とクライアントの一貫性を保つための
要件に応じて、数秒( `max-age=60` )から数時間( `max=age86400` )の間の値に設定する必要があります。

[source,http]
----
Cache-Control: private, must-revalidate, max-age=300
----

{Vary}のデフォルト設定を正しく決めるのはもっと難しいことです。
APIエンドポイントに大きく依存します。例えば、圧縮をサポートするかどうか、
異なるメディアタイプを受け付けるかどうか、他のリクエスト固有のヘッダを
必要とするかどうか、など。正しいキャッシュをサポートするには、この値を
注意深く選択してください。出発点となるデフォルト値は、おそらく以下のものでしょう。

[source,http]
----
Vary: accept, accept-encoding
----

いずれにせよ、これはクライアントに一般的なHTTPレイヤクライアントとプロキシキャッシュを
クライアントが使おうとするときのみ、これが関係してきます。

*注意:* HTTPレベルでの一般的なクライアントとプロキシキャッシュは、設定が難しいです。
それゆえに、(おそらく分散)キャッシュを、アプリケーションのサービス(またはゲートウェイ)レイヤ
に直接用意することを強く推奨します。{Vary}ヘッダの解釈から解放され、{Cache-Control}と
{ETag}ヘッダの理解も非常に単純になります。さらにはキャッシュパフォーマンスやオーバーヘッドに
ついても非常に効率的にもなるし、<<cache-support-patterns, 高度なキャッシュ更新とウォームアップのパターン>>.もサポートできるようになります。

いずれにせよ、どんなクライアントキャッシュやプロキシキャッシュを導入する前には、
{RFC-7234}[RFC 7234] を注意深く読んでください。

