[[proprietary-headers]]
= 独自ヘッダ

このセクションは、独自ヘッダの定義について共有します。
独自ヘッダは、サービス全体にまたがる懸案事項となるため、一貫した名付けをすべきです。
サービスがこれらをサポートするかどうかは任意です。
それゆえOpen APIの仕様には、これを明示的に可視化する正しい場所があります。
リソースのHTTPメソッドのパラメータ定義を使いましょう。

[#183]
== {MUST} 独自Zalandoヘッダのみを使う (訳注: Zalando社の固有ルール)

一般的なルールとして、独自HTTPヘッダは避けるべきというのがあります。エンドトゥエンドで複数のサービスを通して渡される必要があるとそれが効いてきます。
APIの一部分だけではなく、それに続くやり取りに必要とされる文脈情報も与えるようなところで独自ヘッダを用いるのは、妥当なユースケースです。

概念的な観点から、API操作の意味と意図はURLパスとクエリパラメータ、メソッド、コンテントで常に
表現されているべきです。ヘッダはフロー制御やコンテントネゴシエーション、認証のようなプロトコル
に近い機能を実装するのに使われます。
ですので、ヘッダは一般的な文脈情報のために予約されているのです。
({RFC-7231}#section-5[RFC-7231])

`X-` ヘッダは、最初は非標準のパラメータのために予約されていましたが、
`X-` ヘッダを使用は、 {RFC-6648}[RFC 6648] で
廃止予定になりました。
これらのヘッダを使う整合性の取れた方法がないので、ガイドラインにしたがう
APIの利用側・提供側の間でのやりとりの規定は複雑化します。
そのため、ガイドラインではどの `X-` ヘッダを使用するか、どう使われるかを制限しています。

{RFC-6648}[RFC6648] の中で、
企業固有のヘッダの名前には、組織の名前を含むべきだ、という見解を
Internet Engineering Task Force は示しています。
私たちは後方互換の目的で、 `X-` 始まりのヘッダを使い続けています。

次の独自ヘッダは、このガイドラインで使用法が規定されたものです。
HTTPヘッダフィールド名は、大文字・小文字を区別しないことをお忘れなく。

[cols="15%,10%,60%,15%",options="header",]
|=======================================================================
|ヘッダフィールド名 |型 |説明 |値の例
|[[x-flow-id]]{X-Flow-ID} |String |より多くの情報は<<223>>を参照|GKY7oDhpSiKY_gAAAABZ_A

|[[x-tenant-id]]{X-Tenant-ID}|String |マルチテナントのZalandプラットフォームにおいて
リクエストを送信したテナントを識別するためのID。 {X-Tenant-ID}は、OAuthトークンから
抽出したビジネスパートナーIDに応じてセットする。
|9f8b3ca3-4be5-436c-a847-9cd55460c495

|[[x-sales-channel]]{X-Sales-Channel} |String |セールスチャネルは小売が所有していて、
特定の消費者セグメントが、CFA小売カタログを通じて消費者に提供される特定の製品群に向いていることを表現する。
|52b96501-0f8d-43e7-82aa-8a96fab134d7

|[[x-frontend-type]]{X-Frontend-Type}|String |消費者接点のアプリケーション(Consumer facing applications; CFAs)
は、モバイルアプリやブラウザアプリのような異なるフロントエンドのアプリケーションを通じて、
カスタマにビジネスエクスペリエンスを提供する。
例えば特定のクーポンをモバイルにプッシュし使わせるような。
現在、mobile-app, browser, facebook-app, chat-app が使える。
|mobile-app

|[[x-device-type]]{X-Device-Type}|String |デバイスの種類に依存した (機能やコンテンツを含む) カスタマエクスペリエンスを
提供するようなユースケースがある。
このヘッダ情報がその観点で使われるべきである。現在は、smartphone, tablet, desktop, otherが使える。
|tablet

|[[x-device-os]]{X-Device-OS}|String |前述のデバイス種類の上で、デバイスプラットフォーム、例えば
AndroidかiOSかといったようなその違いをハンドリングしたい場合は、これを使う。
現在はiOS, Android, Windows, Linux, MacOSが使える。
|Android

|[[x-mobile-advertising-id]]{X-Mobile-Advertising-Id}|String|
iOSの 
https://developer.apple.com/documentation/adsupport/asidentifiermanager[IDFA] 
(Apple Identifier for mobile Advertising) またはAndroidの 
https://support.google.com/googleplay/android-developer/answer/6048248[GAID] 
(Google mobile Advertising Identifier)である。モバイルデバイスのOSによって与えられるカスタマがリセット可能な一意の識別子であり、パーソナライズド広告に利用される。呼び出されたs-ビスは別のサービスを呼び出すときにこの値も渡すようにしておくべきだ。それぞれのモバイルプラットフォームで、カスタマはこの機能を無効に設定できる。
|b89fadce-1f42-46aa-9c83-b7bc49e76e1f
|=======================================================================

*例外:* このガイドラインの唯一の例外は、 <<153>> の定義として使われる hop-by-hopの
`X-RateLimit-` ヘッダです。

[#184]
== {MUST} 独自ヘッダを伝搬する

すべてのZalandoの独自ヘッダは、End-to-Endのヘッダです。
footnote:header-types[HTTP/1.1 standard ({RFC-7230}#section-6.1[RFC-7230]) では2つのタイプのヘッダが定義されています。end-to-end と hop-by-hop です。
end-to-endヘッダは、リクエストまたはレスポンスの最終的な受け取り手まで
伝達しなければなりません。
一方、hop-by-hopヘッダは、単一のコネクションの間でしか有効でないものです。]

上で定義したすべてのヘッダが、サービスの呼び出しチェーンで伝搬されなければなりません。
ヘッダの名前と値は書き換えてはなりません。

例えば、`X-Device-Type` のようなカスタムヘッダの値は、
デバイス種別の情報を使われ、クエリ結果に直接影響を与えることがあります。またリコメンド結果にも及ぶことがあります。さらにカスタムヘッダの値が、クエリ結果に間接的に影響することもあります。（デバイスタイプの情報がリコメンド結果に間接的に影響するなど）

時々、独自ヘッダの値は、後続のリクエストにおいてエンティティの一部として使われることがあります。
そのような場合は、冗長かもしれませんが、独自ヘッダを後続リクエストのヘッダとしても付けて送らなければなりません。

[#233]
== {MUST} `X-Flow-ID` をサポートする

_Flow-ID_ はサービスのAPIやイベントを通じて渡される汎用のパラメータで、ログファイルやトレースに書かれる。
その結果 _Flow-ID_ を使うと、システム内のコールフローを追うのが簡単になり、特定の呼び出しによって開始されるサービスのアクティビティの関係性が明らかになります。これは運用上のトラブルシューティングやログ分析に非常に役に立ちます。 _Flow-ID_ の主な用途は、当社のSaaSファッションコマースのサービス呼び出しと内部のプロセスフロー(API経由で同期的に実行されたものだけでなく、送出されたイベントによって非同期に実行されるものも)を追跡することです。

=== データ定義

_Flow-ID_ は以下を通じて渡されます。

* {X-Flow-ID} 独自ヘッダを介したRESTful APIリクエスト(<<184>>参照)
* `flow_id`  イベントフィールドをもつ送出されたイベント(<<event-metadata, metadata>>参照)

以下の形式が使えます。

* `UUID` ({RFC-4122}[RFC-4122])
* `base64` ({RFC-4648}[RFC-4648])
* `base64url` ({RFC-4648}#section-5[RFC-4648 Section 5])
* `[a-zA-Z0-9/+_-=]` の文字を使った最大128文字のランダムな一意の文字列

*注意:* もしレガシーなシステムが、特定の形式や長さの _Flow-ID_ しか扱えないならば、そのAPI仕様でこの制限を明記しなければなりません。寛大に不正な文字を削除したり、サポートされた長さに切り詰めたりします。

=== サービスガイド

* サービスは _Flow-ID_ を汎用的な入力としてサポート *しなければならない* ,つまり
** RESTful APIエンドポイントは、リクエストのヘッダで、{X-Flow-ID}を *サポートしなければならない*
** イベントリスナーはイベントから メタデータ `flow-id`  をサポートしなければならない

*注意:*  APIクライアントはサービスを呼び出したり、イベントを生成するときには、 _Flow-ID_ を *付与しなければならない* 。
もし _Flow-ID_ がリクエストやイベントになけｒば、サービスは新たに _Flow-ID_ を生成しなければならない。

* サービスは _Flow_ID_ を伝播しなければならない。つまり、 以下のようなところで _Flow-ID_ を使う。
** 処理中に呼び出したすべてのAPIや送出したすべてのイベントの入力
** ログやトレースに書かれたデータフィールド

*ヒント:* このルールはまた、アプリケーション内部のインタフェースやNakadi経由(訳注: Zalando社のイベントドリブンプラットフォーム)で送出されないイベントにも適用される。