[[api-operation]]
= APIの運用

[#192]
== {MUST} OpenAPI仕様を公開する

すべてのサービスアプリケーションは、外に向けたAPIのOpen APIの仕様を公開しなければなりません。
内部APIは任意ではありますが、APIマネジメント基盤を使うメリットは大きいので、公開しておくに
こしたことはありません。i.e. APIs marked with the
*component-internal* <<219, API audience>> group

APIはその**OpenAPI仕様**を、プロビジョニングサービスをデプロイするのに使われる
**デプロイメント成果物**の中の**/zalando-apis**ディレクトリへコピーすることで公開されます。
ディレクトリは**自己完結型のYAML**
**ファイル**だけを置くようにしてください。そこには1つのAPIについて記述します。
(see
https://docs.google.com/a/zalando.de/document/d/1WBpRHp1DAtz7Pfjt0QwPuZNR1e70APRqUlCCby3JiOM[internal narrative]
for more details).

We prefer this deployment artifact-based method over the
past (now legacy) `.well-known/schema-discovery` service endpoint-based
publishing process, that we only support for backward compatibility reasons.

背景: 動的で複雑な私たちのインフラでは、APIクライアント開発者に、動いているアプリケーションすべての
API仕様を、オンラインからアクセス出来るような場所を提供することが重要です。
インフラの一部として、API公開のプロセスはAPI仕様を探し出すのに使われます。

**注意:** APIを公開するためには、デプロイが成功していることが前提になります。

[#193]
== {SHOULD} API利用状況をモニタリングする

本番環境で使われるAPIのオーナーは、使っているクライアントについて情報を得るために
APIサービスをモニタリングすべきです。その情報は、例えばAPI変更時にレビューをお願い
しなきゃいけない相手を特定するのに役立ちます。

ヒント: クライアントを見つけるより良い方法は、OAuthトークンから取り出したclient-idのログを取ることです。
