[[principles]]
= 原則

[[api-design-principles]]
== API設計の原則

SOAPインタフェースをもつSOA WebサービスとRESTを比較すると、前者はユースケースに特化した
操作を中心に据える傾向があります。一方RESTはビジネス(データ)のエンティティを、URIで識別されるリソースとして
どう見せるか、標準化されたCRUDのようなメソッドで、異なる表現やハイパーメディアを使ってどう操作されうるかを中心に据えます。
RESTful APIは、固有のユースケースからは切り離され、クライアント/サーバの結合を疎にする傾向にあります。
さまざまな新しい業務サービスを構築するために、APIのプラットフォームを提供している(コア)サービスのエコシステムに、
より適したものとなっていきます。
私たちは、その機能がインターネットで提供されるのか、イントラネットで提供されるのかに
かかわらず、すべての種類のアプリケーション、(マイクロ)サービスコンポーネントに、RESTfulウェブサービスの原則を適用します。

* 私たちはJSONペイロードをもったRESTベースのAPIを好む
* 私たちはシステムが、真にRESTfulになることを好む

footnoteref:[fielding-restful,Per definition of R.Fielding REST APIs have to support
HATEOAS (maturity level 3). Our guidelines do not strongly advocate for
full REST compliance, but limited hypermedia usage, e.g. for pagination
(see <<hypermedia>>).
However, we still use the term "RESTful API", due to the absence
of an alternative established term and to keep it like the very majority
of web service industry that also use the term for their REST
approximations — in fact, in today's industry full HATEOAS compliant
APIs are a very rare exception.]

An important principle for API design and usage is Postel's
Law, aka http://en.wikipedia.org/wiki/Robustness_principle[The
Robustness Principle] (see also https://tools.ietf.org/html/rfc1122[RFC 1122]):

* Be liberal in what you accept, be conservative in what you send

_Readings:_ Some interesting reads on the RESTful API design style and service architecture:

* Book:
https://www.amazon.de/Irresistible-APIs-Designing-that-developers/dp/1617292559[Irresistable
APIs: Designing web APIs that developers will love]
* Book:
http://www.amazon.de/REST-Practice-Hypermedia-Systems-Architecture/dp/0596805829[REST
in Practice: Hypermedia and Systems Architecture]
* Book: https://leanpub.com/build-apis-you-wont-hate[Build APIs You
Won't Hate]
* InfoQ eBook: http://www.infoq.com/minibooks/emag-web-api[Web APIs:
From Start to Finish]
* Lessons-learned blog:
http://restful-api-design.readthedocs.org/en/latest/[Thoughts on RESTful
API Design]
* Fielding Dissertation:
http://www.ics.uci.edu/~fielding/pubs/dissertation/top.htm[Architectural
Styles and the Design of Network-Based Software Architectures]


[[api-as-a-product]]
== 製品としてのAPI

前述のとおり、Zalandoは単なるオンラインショップから、価値あるファッションプラットフォームへと
転換しており、ビジネスパートナーのためにSaaP(プラットフォームとしてのソフトウェア)モデル
に続く、製品の豊富な集合を提供しています。
企業として私たちは、これらの製品を(内外問わず)顧客に届けたいのです。

プラットフォームとしての製品とは、(公開)APIで提供される機能群です。
したがってAPIの設計は、製品としての原則に基づくべきなのです。

* APIを製品として扱い、製品のオーナーのように振る舞う
* 顧客の立場に身を置き、彼らのニーズの支持者となる
* 顧客エンジニアにとってAPIがとても魅力的なものになるために、APIのシンプルさ、理解しやすさ、使いやすさを際立たせる
* 長期にわたって、APIをアクティブに改善し、一貫性を維持していく
* 顧客のフィードバックを受け付け、サービスと同レベルのサポートを提供する。

Embracing 'API as a Product' facilitates a service ecosystem which can
be evolved more easily, and used to experiment quickly with new business
ideas by recombining core capabilities.
It makes the difference between agile, innovative product service
business built on a platform of APIs and ordinary enterprise integration business
where APIs are provided as "appendix" of existing products to support system integration
and optimised for local server-side realization.

Understand the concrete use cases of your customers and carefully check
the trade-offs of your API design variants with a product mindset. Avoid short-term
implementation optimizations at the expense of unnecessary client side
obligations, and have a high attention on API quality and client
developer experience.

API as a Product is closely related to our <<100,API First principle>>
(see next chapter) which is more focused on how we engineer high quality APIs.

[[api-first]]
== APIファースト

APIファーストは、私たちの
https://github.com/zalando/engineering-principles[エンジニアリングとアーキテクチャ原則]
の1つです。

手短にいうと、APIファーストは2つの観点を要求します。

* 実装する前に標準仕様言語を使って、まずAPIを定義する
*　同僚やクライアント開発者から、いち早くレビューのフィードバックを得る

コードの外にAPIを定義することで、私たちは早いレビューフィードバックを促し、
サービスインタフェースの設計が、以下に焦点を当てれるような開発の規律にしたいのです。

* ドメインと要求機能の深い理解
* 一般化された業務エンティティ / リソース (つまり、あるユースケース固有のAPIを避ける)
* WHATとHOWの関心の分離。すなわち、実装の観点から「抽象」をを切り離す。APIはたとえ技術スタックが完全に置き換わったとしても、安定しているべきである。

さらには、標準化された仕様のフォーマットによるAPI定義は、また、

* API仕様の拠り所。それはサービスプロバイダとクライアントのユーザの間の重要な契約の1つとなります。
* APIディスカバリ、API GUI、APIドキュメント、API品質の自動チェックなどのAPI基盤ツール。

APIファーストの要素はまた、このAPIガイドラインと同僚やクライアント開発者から、
早期にレビューフィードバックを得るための、APIガイドラインと標準化されたAPIレビュープロセスです。
APIの品質を高め、アーキテクチャと設計の調整を可能にし、サービスプロバイダの開発サイクルに
クライアントアプリケーションの開発が引きずられないようにするために、私たちにとってピアレビューは重要です。

APIファーストが、私たちの愛する*アジャイル開発の原則とかち合わない*ことは重要なことです。
サービスアプリケーションは徐々に進化していくように、APIもまた進化していきます。
もちろんAPI仕様は異なるサイクルで、繰り返し進化を遂げていくでしょうし、そうあるべきですが、
それらはみな、ドラフトの状態と、_早期の_チームとピアレビューフィードバックから始まるのです。

It is important to learn, that API First is *not in conflict with the
agile development principles* that we love. Service applications should
evolve incrementally — and so its APIs. Of course, our API specification
will and should evolve iteratively in different cycles; however, each
starting with draft status and _early_ team and peer review feedback.
API may change and profit from implementation concerns and automated
testing feedback. API evolution during development life cycle may
include breaking changes for not yet productive features and as long as
we have aligned the changes with the clients. Hence, API First does
_not_ mean that you must have 100% domain and requirement understanding
and can never produce code before you have defined the complete API and
get it confirmed by peer review. On the other hand, API First obviously
is in conflict with the bad practice of publishing API definition and
asking for peer review after the service integration or even the service
productive operation has started. It is crucial to request and get early
feedback — as early as possible, but not before the API changes are
comprehensive with focus to the next evolution step and have a certain
quality (including API Guideline compliance), already confirmed via team
internal reviews.
