[[general-guidelines]]
= 全般にわたるガイドライン

タイトルには関連するラベルがついています。: {MUST},
{SHOULD}, {MAY}

[#100]
== {MUST} APIファーストの原則にしたがう

あなたは<<api-first, APIファーストの原則>>にしたがわなければなりません。

* 実装を始める前に、<<101, 仕様記述言語としてOpenAPIを使って>>、まずAPI定義を書かなければならない。
* このガイドラインに沿って一貫性のあるAPIを設計しなければならない。https://zally.zalando.net/[API Linter Service [internal link]]を使うとルールのチェックが自動的におこなえる。
* 同僚やクライアント開発者からのレビューフィードバックを早めに受け取るようにしなければならない。apply our https://github.bus.zalan.do/ApiGuild/ApiReviewProcedure[lightweight API
review process [internal link]] for all <<219, component external APIs>>


[#101]
== {MUST} OpenAPIを使ってAPIの仕様を提供する

私たちはhttp://swagger.io/specification/[OpenAPI](以前はSwaggerと呼ばれていたもの)を、API定義の標準として使っています。APIの設計者はAPI仕様ファイルを、可読性向上のため*YAML*を使って書きます。私たちのツールがOpenAPI 3.0をサポートするまでは、*OpenAPI 2.0*を使うようにしてください。

API仕様はソースコード管理システムを使って、バージョン管理するべきです。一番良いのはAPIの実装コードを同じやり方にしておくことです。

API実装のデプロイと同じタイミングで、API仕様もデプロイするようにします。そうすることでAPIポータルから探せるようになります。
You <<192, must / should publish>> the component <<219, external / internal>> API specification
with the deployment of the implementing service, and, hence, make it discoverable
for the group via our https://apis.zalando.net/[API Portal [internal link]].


[#102]
== {SHOULD} APIのユーザマニュアルを提供する

API仕様に加えて、APIのユーザマニュアルも提供することは、クライアント開発者(とくにそのAPIを使った開発経験があまりない人)にとってとてもありがたいことです。APIユーザマニュアルは、以下のような観点を記述するとよいでしょう。

* APIのスコープ、目的、ユースケース
* 具体的な使用例
* 境界値、エラー時の詳細、修正のヒント
* アーキテクチャと主要な依存関係 (図やシーケンスがあるとよい)

ユーザマニュアルはオンラインで公開されなければなりません。API仕様中の`#/externalDocs/url`プロパティで書かれたリンクを、APIユーザマニュアルに含めるのを忘れないようにしましょう。

[#103]
== {MUST} APIはUS英語で書く
