[[introduction]]
= はじめに

Zalandoのソフトウェアアーキテクチャは、疎結合なマイクロサービスを中心としており、
それらはJSONペイロードをもつRESTful API群によって、機能が提供されています。
小さなエンジニアのチームは、自分たちでAWSアカウントにこれらのマイクロサービスを
デプロイしたり運用したりしています。
私たちのAPIは、その多くが私たちのシステムが何をするのかを完全に表現しており、
それゆえに貴重なビジネス資産となっています。
Zalandoがとあるオンラインショップから価値あるファッションプラットフォームへと変貌を
とげるために、私たちは新しいオープンプラットフォーム戦略の展開をはじめました。
なので、高品質で長持ちするAPIの設計は、私たちにとってよりクリティカルなものになってきているのです。
私たちのビジネスパートナーがサードパーティのアプリケーションから使える公開APIをたくさん
開発することは、私たちの戦略の肝なのです。

私たちは"APIファースト"を、主要なエンジニアリングの原則の1つとして採用しています。
マイクロサービス開発はコードの外にAPIを定義することから始まり、ピアレビューのフィードバックを
十分に取り込みつつ、高品質のAPIへと発展させていきます。
APIファーストは品質に直結する標準を網羅しつつ、軽量なレビュー手順を含んだピアレビューの文化を
育んでいきます。

* APIは理解しやすく習得が簡単である。
* APIは特定の実装やユースケースから汎用的であり抽象化されている。
* APIは堅牢で使うのが簡単である。
* APIは共通の見た目と操作性をもっている。
* APIは一貫したRESTfulなスタイルと文法にしたがう。
* APIは他のチームのAPI群や私たちのグローバルなアーキテクチャとも一貫性をもつ。

[[conventions-used-in-these-guidelines]]
== ガイドラインで使われる規約

本文書では要求レベルのキーワドとして、 "MUST", "MUST NOT", "REQUIRED", "SHALL",
"SHALL NOT", "SHOULD", "SHOULD NOT", "RECOMMENDED", "MAY", "OPTIONAL" が
使われます。
これは https://www.ietf.org/rfc/rfc2119.txt[RFC 2119]の解釈と同様です。

[[zalando-specific-information]]
== Zalando固有の情報

私たちの「RESTful API ガイドライン」の目的は、「一貫したAPIのルックアンドフィール」の品質水準を定めることにあります。チームはAPIの開発においては、このガイドラインを守っていく責務がありますし、またプルリクエストを投げてガイドラインを進化させていくことが求められます。

これらのガイドラインは私たちの仕事が発展していく限り、ずっと「作成中」のステータス
のままでしょう。しかしチームはこれらにしたがい信頼することが、きっと可能なはずです。

変化を続けるガイドラインに対して、次のルールを適用します。

* 既存のAPIは変更する必要がなくても、私たちはそれを推し進めます
* 既存のAPIのクライアントは、古くなったルールにしたがったAPIに対処しなければならない
* 新しいAPIは現在のガイドラインを尊重しなければならない

さらには、いったんAPIが外部に公開されたら、全体の一貫性の維持のために、
最新のガイドラインにしたがって、再レビューし変化させていかなければ
ならないことを、肝に銘じておかなければなりません。
