[[introduction]]
= はじめに

Zalandoのソフトウェアアーキテクチャは、疎結合なマイクロサービスを中心としており、
それらはJSONペイロードをもつRESTful API群によって、機能が提供されています。
小さなエンジニアのチームは、自分たちでAWSアカウントにこれらのマイクロサービスを
デプロイしたり運用したりしています。
私たちのAPIは、その多くが私たちのシステムが何をするのかを完全に表現しており、
それゆえに貴重なビジネス資産となっています。
高品質で長持ちするAPIの設計は、

Zalando’s software architecture centers around decoupled microservices
that provide functionality via RESTful APIs with a JSON payload. Small
engineering teams own, deploy and operate these microservices in their
AWS (team) accounts. Our APIs most purely express what our systems do,
and are therefore highly valuable business assets. Designing
high-quality, long-lasting APIs has become even more critical for us
since we started developing our new open platform strategy, which
transforms Zalando from an online shop into an expansive fashion
platform. Our strategy emphasizes developing lots of public APIs for our
external business partners to use via third-party applications.

私たちは"APIファースト"を、主要なエンジニアリングの原則の1つとして採用しています。
マイクロサービス開発はコードの外にAPIを定義することから始まり、ピアレビューのフィードバックを
十分に取り込みつつ、高品質のAPIへと発展させていきます。
APIファーストは品質に直結する標準を網羅しつつ、軽量なレビュー手順を含んだピアレビューの文化を
育んでいきます。

* APIは理解しやすく習得が簡単である。
* APIは特定の実装やユースケースから汎用的であり抽象化されている。
* APIは堅牢で使うのが簡単である。
* APIは共通の見た目と操作性をもっている。
* APIは一貫したRESTfulなスタイルと文法にしたがう。
* APIは他のチームのAPI群や私たちのグローバルなアーキテクチャとも一貫性をもつ。

Zalando APIが全部同じ人が設計したように見えるのが理想である。

With this in mind, we’ve adopted “API First” as one of our key
engineering principles. Microservices development begins with API
definition outside the code and ideally involves ample peer-review
feedback to achieve high-quality APIs. API First encompasses a set of
quality-related standards and fosters a peer review culture including a
lightweight review procedure. We encourage our teams to follow them to
ensure that our APIs:

* are easy to understand and learn
* are general and abstracted from specific implementation and use cases
* are robust and easy to use
* have a common look and feel
* follow a consistent RESTful style and syntax
* are consistent with other teams’ APIs and our global architecture

Ideally, all Zalando APIs will look like the same author created them.

[[conventions-used-in-these-guidelines]]
== ガイドラインで使われる規約

The requirement level keywords "MUST", "MUST NOT", "REQUIRED", "SHALL",
"SHALL NOT", "SHOULD", "SHOULD NOT", "RECOMMENDED", "MAY", and
"OPTIONAL" used in this document (case insensitive) are to be
interpreted as described in https://www.ietf.org/rfc/rfc2119.txt[RFC
2119].

[[zalando-specific-information]]
== Zalando specific information

The purpose of our “RESTful API guidelines” is to define standards to
successfully establish “consistent API look and feel” quality. The
https://confluence.zalando.net/display/GUL/API+Guild[API Guild [internal
link]] drafted and owns this document. Teams are responsible to fulfill
these guidelines during API development and are encouraged to contribute
to guideline evolution via pull requests.

These guidelines will, to some extent, remain work in progress as our
work evolves, but teams can confidently follow and trust them.

In case guidelines are changing, following rules apply:

* existing APIs don't have to be changed, but we recommend it
* clients of existing APIs have to cope with these APIs based on
outdated rules
* new APIs have to respect the current guidelines

Furthermore you should keep in mind that once an API becomes public
externally available, it has to be re-reviewed and changed according to
current guidelines - for sake of overall consistency.
