[[json-guidelines]]
= JSONガイドライン

ZalandoにおいてJSONデータを定義するのに推奨されるガイドラインです。
JSONとは、ここではhttp://www.rfc-editor.org/rfc/rfc7159.txt[RFC 7159] (which updates
https://www.ietf.org/rfc/rfc4627.txt[RFC 4627])を指します。
"application/json"のメディアタイプとAPIで定義されたカスタムのJSONメディアタイプをもちます。
このガイドラインでは、Zalandoの用語やサービスの用例をもつJSONデータを使って、具体的なケースを示します。
, the “application/json”
media type and custom JSON media types defined for APIs. The guidelines
clarifies some specific cases to allow Zalando JSON data to have an
idiomatic form across teams and services.

最初のいくつかはプロパティ名についてのガイドラインであり、
後半は値についてのガイドラインになります。

[#118]
== {MUST} プロパティ名はASCIIスネークケースでなければならない (キャメルケースは使わない): `^[a-z_][a-z_0-9]*$`

プロパティ名は、ASCII文字列という制限があります。最初の一文字はアルファベットまたはアンダースコアで、
それに続く文字は、アルファベットまたはアンダースコア、数字のいずれかでなくてはなりません。

(`_links`のようなキーワードのみ、`_`から始まるプロパティ名とすることを推奨します)

理念: 確立された標準は存在しませんが、多くの有名インターネット企業は、スネークケースを好みます。
GitHub, Stack Exchange, Twitterなど。一方でGoogleやAmazonは、- だけでなくキャメルケースも
使っています。同じところからくるJSONが一貫したルック・アンド・フィールとなるように設計するのは
必要不可欠なことです。

[#216]
== {SHOULD} キーフォーマットに制限がないmapは、`additionalProperties`を使って定義する

ここで「map」は、文字列のキーから他の型へのマッピングを意味します。
JSONにおいてこれはオブジェクトとして表現されます。キーと値のペアはプロパティ名とプロパティの値によって
表現されます。
OpenAPIスキーマにおいては(JSONスキーマにおいても同様)、それらはadditionalPropertiesを使って
表現すべきとされます。そのようなオフジェクトは他に定義されたプロパティは持ちません。

mapのキーは、命名<<118,ルール 118>>の意味ではプロパティ名とみなしませんので、ドメイン固有のフォーマットに
したがうようにします。
ドキュメントにはmapオブジェクトのスキーマの詳細に、これを記述するようにしてください。
これはそのようなmapの例です。(`transactions`プロパティがそれにあたります)

```yaml
definitions:
  Message:
    description:
      A message together with translations in several languages.
    type: object
    properties:
      message_key:
        type: string
        description: The message key.
      translations:
        description:
          The translations of this message into several languages.
          The keys are https://tools.ietf.org/html/bcp47[BCP-47 language tags].
        type: object
        additionalProperties:
          type: string
          description:
            the translation of this message into the language identified by the key.
```

実際のJSONオブジェクトは次のようなものです。

```json
{ "message_key": "color",
  "translations": {
    "de": "Farbe",
    "en-US": "color",
    "en-GB": "colour",
    "eo": "koloro",
    "nl": "kleur"
  }
}
```

[#120]
== {SHOULD} Arrayの名前は複数形にする

複数の値をもつArrayのプロパティ名は複数形にします。これはオブジェクトの名前は単数形にすべきということも暗に示しています。

[#122]
== {MUST} Booleanのプロパティはnullであってはなりません

booleanとして設計されたJSONプロパティは、スキーマ上nullであってはなりません。
booleanはtrueとfalseの2つの値をもった列挙型です。もしnull値をもちたいことがあれば、
booleanの代わりに列挙型を使うことを強く奨めます。
例えばaccepted_terms_and_conditionsがtrueまたはfalseをもつとき、
これはyes/no/unknownの値をもったterms_and_conditionsに置き換えることができます。

[#123]
== {SHOULD} null値はフィールドごと削除されるべき

共通して使われるSwagger/OpenAPIでは、フィールドがnull値をもつことをサポートしていません。
(もし必須としてマークされていなければ、フィールドごと消すという意図です)

しかしnull値をもつフィールドをクライアント-サーバ間で送受信することは避けられません。
またnullが意味のある値となる場合もあります。JSON Merge Patch (https://tools.ietf.org/html/rfc7386[RFC 7382])は、
プロパティの削除を示すのにnullを使います。

[#124]
== {SHOULD} 空のArray値はnullにはしない

Arrayが空であることは`[]`として曖昧さなく表現できます。

[#125]
== {SHOULD} 列挙型はStringとして表現する

Strings are a reasonable target for values that are by design
enumerations.

[#126]
== {SHOULD} 日付型のプロパティ値はRFC 3339に準拠する

http://tools.ietf.org/html/rfc3339#section-5.6[RFC 3339]で定義された日付と時刻のフォーマットを使いましょう。

* "date"には`年 "-" 月 "-" 日`を使う。例: `2015-05-28`
* "date-time"には `年-月-日 "T" 時:分:秒`を使う, 例: `2015-05-28T14:07:17Z`

https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#data-types[OpenAPI
フォーマット] の"date-time"はRFCの"date-time"に相当し、`2015-05-28`のして表されるOpen APIフォーマットの
"date"は、RFCの"full-date"に相当します。
どちらもspecific profilesで、国際標準http://en.wikipedia.org/wiki/ISO_8601[ISO 8601] のサブセットです。

(リクエストとレスポンスの両方で) ゾーンオフセットが使われる可能性があります。
これも標準で定義されているものです。
しかし、私たちは日付に関しては、オフセットなしのUTCを使うよう制限を設けることを
推奨しています。`2015-05-28T14:07:17+00:00`ではなく、`2015-05-28T14:07:17Z`のように。
これはゾーンオフセットは理解が難しく、正しく扱えないことがよくあることを経験上学んだので、そうしています。
ゾーンオフセットはサマータイムを含むローカルタイムとは異なることに注意してください。
日時のローカライズは、必要ならユーザインタフェースを提供するサービスによってなされるべきです。
保存するときは、すべての日時データはゾーンオフセットなしのUTCで保存します。

時々、数値タイムスタンプで日時を表すデータを見かけますが、
これは精度に関しての解釈の問題を引き起こします。
例えば1460062925というタイムスタンプの表現は、1460062925000 なのか 1460062925.000 なのか
判別できません。日時文字列は冗長でパースが必要ですが、この曖昧さを避けるために必要なことなのです。

[#127]
== {MAY} 期間(durations and intervals)はISO8601に準拠する

ISO 8601で推奨されているフォーマット
Schema based JSON properties that are by design durations and intervals
could be strings formatted as recommended by ISO 8601
(https://tools.ietf.org/html/rfc3339#appendix-A[Appendix A of RFC 3339
contains a grammar] for durations).

[#128]
== {MAY} Standards could be used for Language, Country and Currency

* http://en.wikipedia.org/wiki/ISO_3166-1_alpha-2[ISO 3166-1-alpha2 country]
* (It's "GB", not "UK", even though "UK" has seen some use at Zalando)
* https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes[ISO 639-1 language code]
* https://tools.ietf.org/html/bcp47[BCP-47] (based on ISO 639-1) for language variants
* http://en.wikipedia.org/wiki/ISO_4217[ISO 4217 currency codes]
