[[meta-information]]
= メタ情報

[#218]
== {MUST} APIメタ情報を含める
API仕様はAPI管理のための、次のOpenAPIメタ情報を含まなければならない。

- `#/info/title` as (unique) identifying name of the API
- `#/info/version` to distinguish API specifications versions following
  <<116, semantic rules>>
- `#/info/description` containing a proper description of the API
- `#/info/contact/{name,url,email}` containing the responsible team

Following OpenAPI extension properties *must* be provided in addition:

- `#/info/x-api-id` unique identifier of the API (<<215, see rule 215>>)
- `#/info/x-audience` intended target audience of the API (<<219, see rule 219>>)


[#116]
== {MUST} セマンティックバージョニングを使う

OpenAPIはAPI仕様のバージョンを、`#/info/version`で特定する。
バージョン情報の共通の意味を共有するために、私たちはAPI設計者に
http://semver.org/spec/v2.0.0.html[セマンティックバージョン 2.0]の
ルール`1`から`8`までと`11`に準拠することを期待します。
それは<MAJOR>.<MINOR>.<PATCH>の形式で、次のような意味を与えます。

* 非互換なAPIの変更をしたら、**MAJOR**バージョンをあげる。
* 後方互換性を保ちつつ、新規機能を追加したら、**MINOR**バージョンをあげる。
* 機能に影響のない後方互換性を保ったバグフィクスや表記上の修正をしたら**PATCH**バージョンをあげる。

*Additional Notes:*

* *プレリリース* バージョン(http://semver.org#spec-item-9[rule 9]) と
*ビルドメタデータ* (http://semver.org#spec-item-10[rule 10]) は、
APIバージョン情報に使ってはいけない
* パッチバージョンはtypoの修正になどに役立つけれども、API設計者が、
それをバージョンをあげるかどうかは自由である
* API設計者はAPIバージョン `0.y.z` は、初期API設計のために使うべきである
(http://semver.org/#spec-item-4[rule 4])

* *Pre-release* versions (http://semver.org#spec-item-9[rule 9]) and
*build metadata* (http://semver.org#spec-item-10[rule 10]) must not
be used in API version information.
* While patch versions are useful for fixing typos etc, API designers
are free to decide whether they increment it or not.
* API designers should consider to use API version `0.y.z`
(http://semver.org/#spec-item-4[rule 4]) for initial API design.

例:

[source,yaml]
----
swagger: '2.0'
info:
  title: Parcel Service API
  description: API for <...>
  version: 1.3.7
  <...>
----

[#215]
== {MUST} API識別子を提供する

それぞれのAPIは明示的に、オーナーを割り当て、ユニークでイミュータブルなAPI識別子によって、識別されなければなりません。
APIは進化し続けるので、API識別子を除くすべてのAPIの要素が変わる可能性があります。
API識別子にもとづき一連のAPI仕様を特定し、私たちはAPIのライフサイクルを監視し、APIの履歴や進化を管理しています。
例えば、私たちは
https://github.com/zalando/zally[API Linter Zall]を使って、以前のAPIバージョンに対して、
APIの変更の互換性チェックとセマンティックバージョンの正しさを検証しています。

API識別子は、Open API仕様の`info`-ブロックで定義します。
そしてこれは、次の仕様に準拠しなければなりません。

[source,yaml]
----
/info/x-api-id:
  type: string
  format: urn
  pattern: ^[a-z0-9][a-z0-9-:.]{6,62}[a-z0-9]$
  description: |
    Globally unique and immutable ID required to identify the API. The API
    identifier allows to track the history and evolution of an API as a
    sequence of API specifications.
----


It is responsibility of the API owner to ensure that the application of the
API identifier together with the semantic API <<116,version>> reflect the
expected API history.

自分で管理するURNを使って、可読性のあるAPI識別子を使うのはよいことではありますが、
APIの進化の過程で、API設計者がAPI識別子を変更したくなる衝動がきっと出てくるので、
UUIDを使っておくことをおすすめします。

例:
[source,yaml]
----
swagger: '2.0'
info:
  x-api-id: d0184f38-b98d-11e7-9c56-68f728c1ba70
  title: Parcel Service API
  description: API for <...>
  version: 1.5.8
  <...>
----


https://docs.google.com/document/d/1lRXcTZbZMnFeTVCaazitSWxSdKXGWkOUn99Gr-huNXg[API識別子物語] により情報があります。


[#219]
== {MUST} APIオーディエンスを提供する Provide API Audience

それぞれのAPIはAPIの利用が想定されている対象オーディエンスで分類されなければなりません。
それごとに見つけやすさ、変わりやすさ、設計とドキュメントの品質、権限付与などAPIの異なる標準を
容易にするためです。
私たちは、次に示すようなAPIオーディエンスグループを使って、組織や法的な境界で分類しています。

*component-internal*::
  The API consumers with this audience are restricted to applications of the
  same *functional component* which typically represents a specific *product*
  with clear functional scope and ownership
  (see https://docs.google.com/document/d/1ZSfVkdX_Dwpz22Xl-CFXgxe1u1eY_IfTNdFNMmnGi8c/edit#heading=h.wwteqf6ovyh[details (internal link)]).
  All services of a functional component / product are owned by a specific dedicated owner
  and engineering team(s). Typical examples of component-internal APIs are APIs
  being used by internal helper and worker services or that support service operation.
*business-unit-internal*::
  The API consumers with this audience are restricted to applications of a
  specific product portfolio owned by the same business unit.
*company-internal*::
  The API consumers with this audience are restricted to applications owned
  by the business units of the same the company (e.g. Zalando company with
  Zalando SE, Zalando Payments SE & Co. KG. etc.)
*external-partner*::
  The API consumers with this audience are restricted to applications of
  business partners of the company owning the API and the company itself.
*external-public*::
  APIs with this audience can be accessed by anyone with Internet access.

*注意:* より小さなオーディエンスグループは、より大きなグループに含まれることを意味します。
したがってオーディエンスグループを追加で宣言する必要はありません。

APIオーディエンスは、Open API仕様の`info`-ブロックにAPIメタデータとして含めます。
そして、次の仕様に準拠しなければなりません。

[source,yaml]
----
#/info/x-audience:
  type: string
  x-extensible-enum:
    - component-internal
    - business-unit-internal
    - company-internal
    - external-partner
    - external-public
  description: |
    Intended target audience of the API. Relevant for standards around
    quality of design and documentation, reviews, discoverability,
    changeability, and permission granting.
----

*注意:* API仕様につき、オーディエンスは正確に*1つだけ*です。その理由は、小さなオーディエンスグループは、大きなオーディエンスグループに含まれるからです。もしAPIの一部が異なる対象オーディエンスを持つのであれば、
API仕様を分割することをおすすめします。たとえ冗長だとしてもです。
(https://docs.google.com/document/d/1ff9b6oIa6dyQRyaj36-jmFdtCjWlngnGMsligR4RMIY/edit#heading=h.401bmun50mlj[rationale])

例:

[source,yaml]
----
swagger: '2.0'
info:
  x-audience: company-internal
  title: Parcel Helper Service API
  description: API for <...>
  version: 1.2.4
  <...>
----

オーディエンスグループに関する詳細とより多くの情報は、
https://docs.google.com/document/d/1ff9b6oIa6dyQRyaj36-jmFdtCjWlngnGMsligR4RMIY[
APIオーディエンス物語]にあります
