[[proprietary-headers]]
= 独自ヘッダ

このセクションは、独自ヘッダの定義について共有します。
独自ヘッダは、サービス全体にまたがる懸案事項となるため、一貫した名付けをすべきです。
サービスがこれらをサポートするかどうかは任意です。
それゆえOpenAPIの仕様には、これを明示的に可視化する正しい場所があります。
リソースのHTTPメソッドのパラメータ定義を使いましょう。

[#183]
== {MUST} 独自Zalandoヘッダのみを使う

一般的なルールとして、独自HTTPヘッダは避けるべきというのがあります。
end-to-endで複数サービスを
Still they can be useful in cases where context needs to be passed through
multiple services in an end-to-end fashion.
APIの一部分だけではなく、それに続くやり取りに必要とされる文脈情報も与えるような
ところで独自ヘッダを用いるのは、妥当なユースケースです。

概念的な観点から、API操作の意味と意図はURLパスとクエリパラメータ、メソッド、コンテントで常に
表現されているべきです。ヘッダはフロー制御やコンテントネゴシエーション、認証のようなプロトコル
に近い機能を実装するのに使われます。
ですので、ヘッダは一般的な文脈情報のために予約されているのです。
(https://tools.ietf.org/html/rfc7231#section-5[RFC-7231])

`X-` ヘッダは、最初は非標準のパラメータのために予約されていましたが、
`X-` ヘッダを使用は、 https://tools.ietf.org/html/rfc6648[RFC-6648] で
廃止予定になりました。
これらのヘッダを使う整合性の取れた方法がないので、ガイドラインにしたがう
APIの利用側・提供側の間でのやりとりの規定は複雑化します。
そのため、ガイドラインではどの `X-` ヘッダを使用するか、どう使われるかを制限しています。

The Internet Engineering Task Force's states in
https://tools.ietf.org/html/rfc6648[RFC-6648] that company specific
header' names should incorporate the organization's name. We aim for
backward compatibility, and therefore keep the `X-` prefix.

次の独自ヘッダは、このガイドラインで使用法が規定されたものです。
HTTPヘッダフィールド名は、大文字・小文字を区別しないことをお忘れなく。

[cols="15%,10%,60%,15%",options="header",]
|=======================================================================
|ヘッダフィールド名 |型 |説明 |値の例
|X-Flow-ID |String |リクエストのフローIDで、ログに書かいたり、呼ばれるサービスに渡したりする。
これはトラブルシューティングやログ分析に有用なので、リクエストのトレーサビリティとリクエストフローの識別が
できるようにする。
フローIDは、空白文字なしの印字可能なASCII文字で構成された文字列にするべきある。
ログのパース処理でクラッシュしないように、(改行、タブ、空白、NULLなどの)文字は、
切り捨てるかエスケープするかして、決められたフォーマット・最大長を満たしているかを
検証する。レガシーシステムが特定形式のフローIDしか扱えない場合は、
そのAPIでこれを定義するか、独自のものを生成する必要がある。
|GKY7oDhpSiKY_gAAAABZ_A

|X-Tenant-ID |String |マルチテナントのZalandプラットフォームにおいて
リクエストを送信したテナントを識別するためのID。 X-Tenant-IDは、OAuthトークンから
抽出したビジネスパートナーIDに応じてセットする。
|9f8b3ca3-4be5-436c-a847-9cd55460c495

|X-Sales-Channel |String |セールスチャネルは小売が所有していて、
特定の消費者セグメントが、CFA小売カタログを通じて消費者に提供される
特定の製品群に向いていることを表現する。
|52b96501-0f8d-43e7-82aa-8a96fab134d7

|X-Frontend-Type |String |消費者接点のアプリケーション(Consumer facing applications; CFAs)
は、モバイルアプリやブラウザアプリのような異なるフロントエンドのアプリケーションを通じて、
カスタマにビジネスエクスペリエンスを提供する。
例えば特定のクーポンをモバイルにプッシュし使わせるような。
現在、mobile-app, browser, facebook-app, chat-app が使える。
|mobile-app

|X-Device-Type |String |デバイスの種類に依存した (機能やコンテンツを含む) カスタマエクスペリエンスを
提供するようなユースケースがある。
このヘッダ情報がその観点で使われるべきである。現在は、smartphone, tablet, desktop, otherが使える。
|tablet

|X-Device-OS |String |前述のデバイス種類の上で、デバイスプラットフォーム、例えば
AndroidかiOSかといったようなその違いをハンドリングしたい場合は、これを使う。
現在はiOS, Android, Windows, Linux, MacOSが使える。
|Android

|X-App-Domain |Integer |リクエストのアプリケーションドメイン。
app-domainはレガシーな概念で、新しいプラットフォームでは小売、販売チャネル、国のような
CFAの主要な関心事の組合せに置き換わるだろう。
|16
|=======================================================================

*例外:* このガイドラインの唯一の例外は、 <<153>> の定義として使われる hop-by-hopの
`X-RateLimit-` ヘッダです。

[#184]
== {MUST} 独自ヘッダを伝搬する

すべてのZalandoの独自ヘッダは、End-to-Endのヘッダです。
footnoteref:[header-types, HTTP/1.1 standard
(https://tools.ietf.org/html/rfc7230#section-6.1[RFC-7230]) では
2つのタイプのヘッダが定義されています。end-to-end と hop-by-hop です。

end-to-endヘッダは、リクエストまたはレスポンスの最終的な受け取り手まで
伝達しなければなりません。
一方、hop-by-hopヘッダは、単一のコネクションの間でしか有効でないものです。]

上で定義したすべてのヘッダが、サービスの呼び出しチェーンで伝搬されなければなりません。
ヘッダの名前と値は書き換えてはなりません。

例えば、`X-Device-Type`のようなカスタムヘッダの値は、
デバイス種別の情報を使われ、クエリ結果に影響を与えることがあります。
またリコメンド結果にも及ぶことがあります。

時々、独自ヘッダの値は、後続のリクエストにおいてエンティティの一部として使われることがあります。
そのような場合は、冗長かもしれませんが、独自ヘッダを後続リクエストのヘッダとしても付けて送らなければなりません。
