[[proprietary-headers]]
= 独自ヘッダ

このセクションは、一貫した名付けをすべき独自ヘッダの定義について共有します。
サービスが
それゆえOpenAPIの仕様には、これを明示的に可視化する正しい場所があります。

This section shares definitions of proprietary headers that should be
named consistently because they address overarching service-related
concerns. Whether services support these concerns or not is optional;
therefore, the OpenAPI API specification is the right place to make this
explicitly visible. Use the parameter definitions of the resource HTTP
methods.

[#183]
== {MUST} Zalandoヘッダのみを使う Use Only the Specified Proprietary Zalando Headers

As a general rule, proprietary HTTP headers should be avoided. Still
they can be useful in cases where context needs to be passed through
multiple services in an end-to-end fashion. As such, a valid use-case
for a proprietary header is providing context information, which is not
a part of the actual API, but is needed by subsequent communication.

From a conceptual point of view, the semantics and intent of an
operation should always be expressed by URLs path and query parameters,
the method, and the content. Headers are more often used to implement
functions close to the protocol considerations, such as flow control,
content negotiation, and authentication. Thus, headers are reserved for
general context information
(https://tools.ietf.org/html/rfc7231#section-5[RFC-7231]).

`X-` headers were initially reserved for unstandardized parameters, but
the usage of `X-` headers is deprecated
(https://tools.ietf.org/html/rfc6648[RFC-6648]). This complicates the
contract definition between consumer and producer of an API following
these guidelines, since there is no aligned way of using those headers.
Because of this, the guidelines restrict which `X-` headers can be used
and how they are used.

The Internet Engineering Task Force's states in
https://tools.ietf.org/html/rfc6648[RFC-6648] that company specific
header' names should incorporate the organization's name. We aim for
backward compatibility, and therefore keep the `X-` prefix.

The following proprietary headers have been specified by this guideline
for usage so far. Remember that HTTP header field names are not
case-sensitive.

[cols="15%,10%,60%,15%",options="header",]
|=======================================================================
|Header field name |Type |Description |Header field value example
|X-Flow-ID |String |The flow id of the request, which is written into
the logs and passed to called services. Helpful for operational
troubleshooting and log analysis. It supports traceability of requests
and identifying request flows through system of many services. It should
be a string consisting of just printable ASCII characters (i.e. without
whitespace). Verify in a received request that it fits to a specific
format, has a sensible maximum length and possibly throw out or escape
characters/bytes which could crash your log parsing (line breaks, tabs,
spaces, NULL). If a legacy subsystem can only work with flow IDs of a
specific format, it needs to define this in its API, or make its own
ones. |GKY7oDhpSiKY_gAAAABZ_A

|X-Tenant-ID |String | Identifies the tenant initiated the request
to the multi tenant Zalando Platform. The X-Tenant-ID must be set
according to the Business Partner ID extracted from the OAuth token when
a request from a Business Partner hits the Zalando Platform.
|9f8b3ca3-4be5-436c-a847-9cd55460c495

|X-Sales-Channel |String |Sales channels are owned by retailers and
represent a specific consumer segment being addressed with a specific
product assortment that is offered via CFA retailer catalogs to
consumers (see
https://pages.github.bus.zalan.do/core-platform/docs/glossary/glossary.html[platform
glossary [internal link]]) |52b96501-0f8d-43e7-82aa-8a96fab134d7

|X-Frontend-Type |String |Consumer facing applications (CFAs) provide
business experience to their customers via different frontend
application types, for instance, mobile app or browser. Info should be
passed-through as generic aspect -- there are diverse concerns, e.g.
pushing mobiles with specific coupons, that make use of it. Current
range is mobile-app, browser, facebook-app, chat-app |mobile-app

|X-Device-Type |String |There are also use cases for steering customer
experience (incl. features and content) depending on device type. Via
this header info should be passed-through as generic aspect. Current
range is smartphone, tablet, desktop, other |tablet

|X-Device-OS |String |On top of device type above, we even want to
differ between device platform, e.g. smartphone Android vs. iOS. Via
this header info should be passed-through as generic aspect. Current
range is iOS, Android, Windows, Linux, MacOS |Android

|X-App-Domain |Integer |The app domain (i.e. shop channel context) of
the request. Note, app-domain is a legacy concept that will be replaced
in new platform by combinations of main CFA concerns like retailer,
sales channel, country |16
|=======================================================================

*例外:* The only exception to this guideline are the conventional
hop-by-hop `X-RateLimit-` headers which can be used as defined in <<153>>.

[#184]
== {MUST} 独自ヘッダを伝搬する

すべてのZalandoの独自ヘッダは、End-to-Endのヘッダです。
footnoteref:[header-types, HTTP/1.1 standard
(https://tools.ietf.org/html/rfc7230#section-6.1[RFC-7230]) では
2つのタイプのヘッダが定義されています。end-to-end と hop-by-hop です。

end-to-endヘッダは、リクエストまたはレスポンスの最終的な受け取り手まで
伝達しなければなりません。
一方、hop-by-hopヘッダは、単一のコネクションの間でしか有効でないものです。]

上で定義したすべてのヘッダが、サービスの呼び出しチェーンで伝搬されなければなりません。
ヘッダの名前と値は書き換えてはなりません。

例えば、`X-Device-Type`のようなカスタムヘッダの値は、
デバイス種別の情報を使われ、クエリ結果に影響を与えることがあります。
またリコメンド結果にも及ぶことがあります。

時々、独自ヘッダの値は、後続のリクエストにおいてエンティティの一部として使われることがあります。
そのような場合は、冗長かもしれませんが、独自ヘッダを後続リクエストのヘッダとしても付けて送らなければなりません。
