[[security]]
= セキュリティ

[#104]
== {MUST} OAuth 2.0でエンドポイントをセキュアにする

すべてのAPIエンドポイントはOAuth 2.0を使ってセキュアにする必要があります。
API仕様におけるセキュリティ定義のやり方は、
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#security-definitions-object[公式のOpenAPI仕様] を参照してください。
次に例も示しておきます。

[source,yaml]
----
securityDefinitions:
  oauth2:
    type: oauth2
    flow: application
    tokenUrl: https://identity.zalando.com/oauth2/token
    scopes:
      fulfillment-order-service.read: Access right needed to read from the fulfillment order service.
      fulfillment-order-service.write: Access right needed to write to the fulfillment order service.
----

上記例はセキュリティ標準として、エンドポイントへのアクセスを認証するのに
クライアント認証フローのOAuth2を使った際の定義です。
さらに、スコープセクションを使って2つのAPIアクセス権を定義しています。
エンドポイントの権限の使い方は後述します。次のセクションを参照ください。

`securityDefinitions` でOAuthトークンを取得するフローを指定するのは、ほとんど意味がありません。
APIエンドポイントは、どうOAuthトークンが生成されようが気にする必要はありません。
不幸にも `flow` フィールドは必須であり、消すことはできません。
APIエンドポイントは、常に `flow: application` を設定し、
この情報は無視するべきです。

[#105]
== {MUST} アクセス権限を定義し割り当てる (スコープ)

すべてのAPIはアクセス権(ここではスコープと呼ぶ) を定義する必要があります。
そして、すべてのAPIエンドポイントには、少なくとも1つのスコープを割り当てる必要があります。
前セクションで示したように、スコープはAPI仕様ごとに名前とその説明によって定義します。
スコープ名を決めるとき、次のルールを参照するようにしてください。

[source,bnf]
----
<api-scope> ::= <api-standard-scope> |            -- 大部分のユースケースでこれを使うべき
                <api-resource-specific-scope> |   -- 異なるユースケースへの特別なセキュリティアクセスのため
                <api-pseudo-scope>                -- アクセスが制限されないことを明示的に指し示すのに使う

<api-standard-scope>          ::= <application-id>.<access-type>
<api-resource-specific-scope> ::= <application-id>.<resource-id>.<access-type>
<api-pseudo-scope>            ::= uid

<application-id> ::= <STUPSで定義さたもの>
<access-type>    ::= read | write           -- 将来拡張されるかもしれない
<resource-id>    ::= <application-id 文法にしたがう自由な識別子>
----

APIはデフォルトでは標準のスコープを使うべきです。大概のユースケースでは、(read と write
違いで)特定のAPIへのアクセスを制限することは、荷主か小売か、カスタマか運用スタッフか、といった
クライアントの種類によってアクセスを制御するのに十分なものです。
私たちはスコープが多く、細かくなりすぎないようにしたいと考えています。
それはなんら付加価値を産まず複雑さだけが増していくからです。
ただ、APIが異なるオーナーには異なるリソースを返すような状況下では、
リソース固有のスコープは意味があるかもしれません。

標準とリソース固有のスコープの例を以下に示します。

[cols="25%,20%,20%,35%",options="header",]
|=======================================================================
|Application ID |Resource ID |Access Type |Example
|`fulfillment-order` | |`read` |`fulfillment-order.read`

|`fulfillment-order` | |`write` |`fulfillment-order.write`

|`sales-order` |`sales_order` |`read` |`sales-order.sales_order.read`

|`sales-order` |`shipment_order` |`read`
|`sales-order.shipment_order.read`
|=======================================================================

スコープ名を定義し、スコープをAPI仕様の先頭でセキュリティ定義として宣言したら、
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#securityRequirementObject[`セキュリティ` 要求] を記述して、以下のように各API操作に割り当てます。

[source,yaml]
----
paths:
  /sales-orders/{order-number}:
    get:
      summary: Retrieves a sales order
      security:
        - oauth2:
          - sales-order-service.sales_order.read
----

非常にレアケースですが、API全体または、その内いくつかのエンドポイントが、特定のアクセス制御を必要としない
ことがあります。しかし、この場合も `uid` の疑似アクセス権スコープを明示的に割り当てるようにすべきです。
これはユーザIDで、OAuth2のデフォルトスコープとして常に利用できます。

[source,yaml]
----
paths:
  /public-information:
    get:
      summary: Provides public information about ...
               Accessible by any user; no access rights needed.
      security:
        - oauth2:
          - uid
----

ヒント: "Authorization" ヘッダを明示的に定義する必要はありません。
セキュリティセクションが定義されていれば、暗黙的にそれは標準ヘッダとなるからです。
